CREATE TABLE IF NOT EXISTS proma_zarinpal_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  setting_key VARCHAR(100) NOT NULL,
  setting_value LONGTEXT NULL,
  encrypted_value LONGTEXT NULL,
  is_secret TINYINT(1) NOT NULL DEFAULT 0,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_proma_zarinpal_setting_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proma_zarinpal_transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid CHAR(36) NOT NULL,
  local_order_id VARCHAR(100) NOT NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  customer_id BIGINT UNSIGNED NOT NULL,
  contract_id BIGINT UNSIGNED NOT NULL,
  installment_id BIGINT UNSIGNED NULL,
  payment_group_id BIGINT UNSIGNED NULL,
  payment_id BIGINT UNSIGNED NULL,
  environment VARCHAR(20) NOT NULL,
  merchant_fingerprint CHAR(64) NOT NULL,
  merchant_snapshot_encrypted LONGTEXT NOT NULL,
  internal_amount_toman DECIMAL(18,2) NOT NULL,
  gateway_amount BIGINT UNSIGNED NOT NULL,
  gateway_currency CHAR(3) NOT NULL,
  description VARCHAR(255) NOT NULL,
  authority VARCHAR(100) NULL,
  ref_id VARCHAR(100) NULL,
  card_pan_masked VARCHAR(32) NULL,
  card_hash VARCHAR(191) NULL,
  fee BIGINT UNSIGNED NOT NULL DEFAULT 0,
  fee_type VARCHAR(40) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'created',
  callback_status VARCHAR(20) NULL,
  request_code INT NULL,
  request_message VARCHAR(255) NULL,
  verify_code INT NULL,
  verify_message VARCHAR(255) NULL,
  error_code VARCHAR(80) NULL,
  recovery_status VARCHAR(50) NULL,
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  requested_at DATETIME NULL,
  redirected_at DATETIME NULL,
  callback_at DATETIME NULL,
  verifying_at DATETIME NULL,
  verified_at DATETIME NULL,
  failed_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_proma_zarinpal_uuid (uuid),
  UNIQUE KEY uq_proma_zarinpal_local_order (local_order_id),
  UNIQUE KEY uq_proma_zarinpal_idempotency (idempotency_key),
  UNIQUE KEY uq_proma_zarinpal_environment_authority (environment, authority),
  KEY idx_proma_zarinpal_customer (customer_id),
  KEY idx_proma_zarinpal_contract (contract_id),
  KEY idx_proma_zarinpal_installment (installment_id),
  KEY idx_proma_zarinpal_group (payment_group_id),
  KEY idx_proma_zarinpal_status (status),
  KEY idx_proma_zarinpal_ref_id (ref_id),
  KEY idx_proma_zarinpal_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proma_zarinpal_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  transaction_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(80) NOT NULL,
  level VARCHAR(20) NOT NULL DEFAULT 'info',
  provider_code VARCHAR(40) NULL,
  message VARCHAR(255) NOT NULL,
  context_json LONGTEXT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_proma_zarinpal_logs_transaction (transaction_id),
  KEY idx_proma_zarinpal_logs_event (event_type),
  KEY idx_proma_zarinpal_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
