<?php
require_once __DIR__ . '/components/ui.php';
$query = ['q' => $_GET['q'] ?? '', 'balance' => $_GET['balance'] ?? '', 'role' => $_GET['role'] ?? '', 'status' => $_GET['status'] ?? '', 'sort' => $_GET['sort'] ?? 'name'];
?>
<div class="proma-accounting proma-accounting-accounts">
  <?php pa_page_header('گردش حساب کاربران', 'حساب کاربران', 'مانده، کمیسیون و آخرین فعالیت مدیران، اپراتورها و وکلا را بررسی کنید.', 'users'); ?>
  <section class="proma-accounting-balance-guide"><h3>قاعده اثر عملیات</h3><div><strong>پرداخت به کاربر</strong><span>با علامت منفی، مانده را کاهش می‌دهد.</span></div><div><strong>دریافت از کاربر</strong><span>با علامت مثبت، مانده را افزایش می‌دهد.</span></div></section>
  <section class="proma-accounting-panel">
    <form method="get" class="proma-accounting-filter-bar"><input type="hidden" name="route" value="plugin/accounting/accounts"><div class="proma-accounting-control"><input name="q" value="<?= e($query['q']) ?>" placeholder="جستجو با نام، موبایل یا نام کاربری" aria-label="جستجوی حساب کاربران"></div><div class="proma-accounting-control"><select name="role" aria-label="فیلتر نقش"><option value="">همه نقش‌ها</option><?php foreach (['admin' => 'مدیر', 'operator' => 'اپراتور', 'lawyer' => 'وکیل'] as $value => $label): ?><option value="<?= e($value) ?>"<?= $query['role'] === $value ? ' selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="proma-accounting-control"><select name="balance" aria-label="فیلتر مانده"><option value="">همه مانده‌ها</option><option value="positive"<?= $query['balance'] === 'positive' ? ' selected' : '' ?>>مانده مثبت</option><option value="negative"<?= $query['balance'] === 'negative' ? ' selected' : '' ?>>مانده منفی</option><option value="zero"<?= $query['balance'] === 'zero' ? ' selected' : '' ?>>مانده صفر</option></select></div><div class="proma-accounting-control"><select name="status" aria-label="وضعیت حساب"><option value="">همه وضعیت‌ها</option><option value="active"<?= $query['status'] === 'active' ? ' selected' : '' ?>>فعال</option><option value="inactive"<?= $query['status'] === 'inactive' ? ' selected' : '' ?>>غیرفعال</option></select></div><div class="proma-accounting-control"><select name="sort" aria-label="مرتب‌سازی"><option value="name"<?= $query['sort'] === 'name' ? ' selected' : '' ?>>بر اساس نام</option><option value="balance_desc"<?= $query['sort'] === 'balance_desc' ? ' selected' : '' ?>>بیشترین مانده</option><option value="balance_asc"<?= $query['sort'] === 'balance_asc' ? ' selected' : '' ?>>کمترین مانده</option><option value="recent"<?= $query['sort'] === 'recent' ? ' selected' : '' ?>>آخرین فعالیت</option></select></div><button class="btn btn-primary" type="submit"><i data-feather="search"></i><span>اعمال فیلتر</span></button></form>
    <?php if (!empty($accounts)): ?>
      <div class="proma-accounting-table-shell is-card-mobile"><table class="proma-accounting-table"><thead><tr><th>کاربر</th><th>مانده فعلی</th><th>کمیسیون</th><th>افزایش‌ها</th><th>کاهش‌ها</th><th>آخرین تراکنش</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody><?php foreach ($accounts as $account): ?><tr><td><?= pa_user_cell($account) ?></td><td data-label="مانده"><?= pa_balance($account['balance'] ?? 0) ?></td><td data-label="کمیسیون"><?= money_toman($account['total_commission'] ?? 0) ?></td><td data-label="افزایش‌ها" class="proma-accounting-positive">+ <?= money_toman($account['total_increase'] ?? 0) ?></td><td data-label="کاهش‌ها" class="proma-accounting-negative">- <?= money_toman($account['total_decrease'] ?? 0) ?></td><td data-label="آخرین تراکنش"><?= !empty($account['last_transaction_at']) ? e(jdatetime($account['last_transaction_at'])) : 'بدون تراکنش' ?></td><td><?= pa_status($account['account_status'] ?? 'active') ?></td><td><a class="proma-accounting-icon-button" href="<?= e(url('plugin/accounting/ledger/' . (int) $account['id'], ['action' => $_GET['action'] ?? ''])) ?>" aria-label="مشاهده دفترکل <?= e($account['full_name']) ?>" title="مشاهده دفترکل"><i data-feather="book-open"></i></a></td></tr><?php endforeach; ?></tbody></table></div>
      <div class="proma-accounting-mobile-list"><?php foreach ($accounts as $account): ?><article class="proma-accounting-data-card"><div class="proma-accounting-data-card-header"><?= pa_user_cell($account) ?><?= pa_status($account['account_status'] ?? 'active') ?></div><div class="proma-accounting-data-card-grid"><div><span>مانده فعلی</span><strong><?= money_toman($account['balance'] ?? 0) ?></strong></div><div><span>کل کمیسیون</span><strong><?= money_toman($account['total_commission'] ?? 0) ?></strong></div><div><span>افزایش‌ها</span><strong class="proma-accounting-positive">+ <?= money_toman($account['total_increase'] ?? 0) ?></strong></div><div><span>کاهش‌ها</span><strong class="proma-accounting-negative">- <?= money_toman($account['total_decrease'] ?? 0) ?></strong></div><div><span>آخرین فعالیت</span><strong><?= !empty($account['last_transaction_at']) ? e(jdatetime($account['last_transaction_at'])) : 'بدون تراکنش' ?></strong></div></div><div class="proma-accounting-data-card-actions"><a class="btn btn-primary btn-sm" href="<?= e(url('plugin/accounting/ledger/' . (int) $account['id'], ['action' => $_GET['action'] ?? ''])) ?>"><i data-feather="book-open"></i><span>مشاهده دفترکل</span></a></div></article><?php endforeach; ?></div>
      <?= render_pagination($pagination ?? [], static function ($page) use ($query) { return url('plugin/accounting/accounts', array_merge($query, ['page' => $page])); }) ?>
    <?php else: ?><?= pa_empty_state('حسابی پیدا نشد', 'فیلترها را تغییر دهید یا نام و شماره تماس دیگری جستجو کنید.', 'search') ?><?php endif; ?>
  </section>
</div>
