<?php require_once __DIR__ . '/components/ui.php'; $summary = $summary ?? []; $chart = $chart ?? ['labels'=>[],'rows'=>[]]; $self = $self ?? true; ?>
<div class="proma-accounting proma-accounting-analytics" data-accounting-analytics>
  <?php pa_page_header($self ? 'داشبورد مالی من' : 'تحلیل مالی کاربران', $self ? 'داشبورد مالی من' : 'تحلیل مالی کاربران', 'گزارش درآمد، هزینه و خالص عملکرد مالی؛ این گزارش صورت سود و زیان رسمی شرکت نیست.', 'activity'); ?>
  <?php if (!$self): ?><form method="get" action="<?= e(url('plugin/accounting/analytics/users')) ?>" class="proma-accounting-filter-bar"><label>شناسه کاربر<input type="number" name="user_id" value="<?= (int) ($selectedUserId ?? 0) ?>" min="1" required></label><label>از تاریخ<input type="text" name="start_date" value="<?= e($_GET['start_date'] ?? '') ?>" placeholder="۱۴۰۴/۰۱/۰۱"></label><label>تا تاریخ<input type="text" name="end_date" value="<?= e($_GET['end_date'] ?? '') ?>" placeholder="۱۴۰۴/۰۱/۳۱"></label><button class="btn btn-primary" type="submit">نمایش تحلیل</button></form><?php endif; ?>
  <div class="proma-accounting-kpis">
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-label">مانده فعلی</span><strong><?= money_toman($summary['balance'] ?? 0) ?></strong></article>
    <article class="proma-accounting-kpi is-positive"><span class="proma-accounting-kpi-label">درآمد ماه</span><strong><?= money_toman($summary['income'] ?? 0) ?></strong></article>
    <article class="proma-accounting-kpi is-negative"><span class="proma-accounting-kpi-label">هزینه ماه</span><strong><?= money_toman($summary['expense'] ?? 0) ?></strong></article>
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-label">خالص عملکرد مالی</span><strong><?= money_toman($summary['net_result'] ?? 0) ?></strong><small><?= (int) ($summary['net_result'] ?? 0) > 0 ? 'خالص مثبت' : ((int) ($summary['net_result'] ?? 0) < 0 ? 'خالص منفی' : 'بدون تغییر خالص') ?></small></article>
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-label">کمیسیون</span><strong><?= money_toman($summary['commission'] ?? 0) ?></strong></article>
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-label">حقوق ثابت</span><strong><?= money_toman($summary['salary'] ?? 0) ?></strong></article>
  </div>
  <section class="proma-accounting-panel"><h3>روند روزانه</h3><p>دادهٔ نمودار با یک aggregation تجمیعی بارگذاری شده و polling ندارد.</p><div class="proma-accounting-table-shell"><table class="proma-accounting-table"><thead><tr><th>تاریخ</th><th>درآمد</th><th>هزینه</th><th>خالص</th><th>کمیسیون</th></tr></thead><tbody><?php foreach (($chart['rows'] ?? []) as $row): ?><tr><td><?= e($row['bucket']) ?></td><td><?= money_toman($row['income']) ?></td><td><?= money_toman($row['expense']) ?></td><td><?= money_toman((int) $row['income'] - (int) $row['expense']) ?></td><td><?= money_toman($row['commission']) ?></td></tr><?php endforeach; ?><?php if (empty($chart['rows'])): ?><tr><td colspan="5" class="empty">داده‌ای برای بازه انتخاب‌شده وجود ندارد.</td></tr><?php endif; ?></tbody></table></div></section>
  <section class="proma-accounting-panel"><h3>آخرین اسناد</h3><div class="proma-accounting-table-shell"><table class="proma-accounting-table"><thead><tr><th>تاریخ</th><th>نوع</th><th>مبلغ</th><th>شرح</th></tr></thead><tbody><?php foreach (($summary['recent'] ?? []) as $entry): ?><tr><td><?= e($entry['entry_date']) ?></td><td><?= e($entry['entry_type']) ?></td><td><?= money_toman($entry['amount']) ?></td><td><?= e($entry['description']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
