<div class="proma-accounting proma-accounting-dashboard">
  <header class="proma-accounting-page-header"><div><span class="proma-accounting-eyebrow">نمای مالی</span><h2>داشبورد حسابداری</h2><p>خلاصه فروش‌ها، کمیسیون‌ها و گردش حساب کاربران.</p></div><div class="proma-accounting-header-actions"><a class="btn btn-light" href="<?= e(url('plugin/accounting/help')) ?>"><i data-feather="book-open"></i><span>راهنما</span></a><a class="btn btn-primary" href="<?= e(url('plugin/accounting/accounts')) ?>"><i data-feather="users"></i><span>حساب کاربران</span></a></div></header>
  <div class="proma-accounting-kpis">
    <div class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-blue"><i data-feather="users"></i></span><div><span>کاربران حسابداری</span><strong><?= to_persian_digits($summary['users'] ?? 0) ?></strong></div></div>
    <div class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-green"><i data-feather="shopping-bag"></i></span><div><span>فروش‌های ثبت‌شده</span><strong><?= to_persian_digits($summary['sales'] ?? 0) ?></strong></div></div>
    <div class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-amber"><i data-feather="percent"></i></span><div><span>کمیسیون باز</span><strong><?= money_toman($summary['commission'] ?? 0) ?></strong></div></div>
    <div class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-purple"><i data-feather="book"></i></span><div><span>خالص دفترکل</span><strong><?= money_toman($summary['ledger'] ?? 0) ?></strong></div></div>
  </div>
  <section class="proma-accounting-balance-guide"><h3>قاعده مانده در پرما پی</h3><div><strong>پرداخت وجه به شخص</strong><span>مانده حساب شخص را کاهش می‌دهد.</span></div><div><strong>دریافت وجه از شخص</strong><span>مانده حساب شخص را افزایش می‌دهد.</span></div></section>
  <section class="proma-accounting-panel"><div class="proma-accounting-section-heading"><div><span class="proma-accounting-section-icon"><i data-feather="clock"></i></span><div><h3>حساب‌های اخیر</h3><p>آخرین وضعیت مانده کاربران داخلی</p></div></div><a class="btn btn-sm btn-light" href="<?= e(url('plugin/accounting/accounts')) ?>">فهرست کامل</a></div><div class="table-responsive"><table class="table proma-accounting-table"><thead><tr><th>کاربر</th><th>نقش</th><th>شماره حساب</th><th>مانده</th><th>عملیات</th></tr></thead><tbody><?php foreach (($accounts ?? []) as $account): ?><tr><td><strong><?= e($account['full_name']) ?></strong></td><td><?= e(role_label($account['role'])) ?></td><td dir="ltr"><?= e($account['account_number'] ?: '-') ?></td><td class="<?= (float) ($account['balance'] ?? 0) >= 0 ? 'proma-accounting-positive' : 'proma-accounting-negative' ?>"><?= money_toman($account['balance']) ?></td><td><a class="btn btn-sm btn-light" href="<?= e(url('plugin/accounting/ledger/' . (int) $account['id'])) ?>"><i data-feather="book-open"></i><span>دفترکل</span></a></td></tr><?php endforeach; ?><?php if (empty($accounts)): ?><tr><td colspan="5" class="empty">حسابی ثبت نشده است.</td></tr><?php endif; ?></tbody></table></div></section>
</div>
