<?php
require_once __DIR__ . '/components/ui.php';
$currentBalance = (int) ($balance ?? 0);
$accountSummary = $accountSummary ?? [];
$requestedAction = in_array($_GET['action'] ?? '', ['payment', 'receipt', 'expense', 'bonus', 'deduction'], true) ? $_GET['action'] : 'bonus';
ob_start();
?><a class="btn btn-light" href="<?= e(url('plugin/accounting/accounts')) ?>"><i data-feather="arrow-right"></i><span>بازگشت به حساب‌ها</span></a><a class="btn btn-light" href="<?= e(url('plugin/accounting/help', ['section' => 'ledger'])) ?>"><i data-feather="help-circle"></i><span>راهنما</span></a><?php
$headerActions = trim(ob_get_clean());
?>
<div class="proma-accounting proma-accounting-ledger">
  <?php pa_page_header('دفترکل کاربر', $accountUser['full_name'] ?? 'حساب کاربر', 'ثبت عملیات و مشاهده تاریخچه تغییرات مانده با حفظ کامل سوابق حسابرسی.', 'book-open', $headerActions); ?>

  <div class="proma-accounting-kpis">
    <article class="proma-accounting-kpi <?= $currentBalance >= 0 ? 'is-positive' : 'is-negative' ?>"><span class="proma-accounting-kpi-icon is-purple"><i data-feather="credit-card"></i></span><div><span class="proma-accounting-kpi-label">مانده فعلی</span><strong><?= money_toman($currentBalance) ?></strong><small><?= $currentBalance > 0 ? 'مطالبه کاربر از مجموعه' : ($currentBalance < 0 ? 'بدهی کاربر به مجموعه' : 'حساب تسویه است') ?></small></div></article>
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-green"><i data-feather="plus-circle"></i></span><div><span class="proma-accounting-kpi-label">مجموع افزایش‌ها</span><strong><?= money_toman($accountSummary['total_increase'] ?? 0) ?></strong><small>کمیسیون، پاداش، هزینه و دریافت</small></div></article>
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-red"><i data-feather="minus-circle"></i></span><div><span class="proma-accounting-kpi-label">مجموع کاهش‌ها</span><strong><?= money_toman($accountSummary['total_decrease'] ?? 0) ?></strong><small>پرداخت، کسورات و اصلاحات کاهشی</small></div></article>
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-purple"><i data-feather="percent"></i></span><div><span class="proma-accounting-kpi-label">کمیسیون ثبت‌شده</span><strong><?= money_toman($accountSummary['total_commission'] ?? 0) ?></strong><small>اسناد افزایشی کمیسیون این کاربر</small></div></article>
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-blue"><i data-feather="send"></i></span><div><span class="proma-accounting-kpi-label">پرداخت‌شده به کاربر</span><strong><?= money_toman($accountSummary['paid_to_user'] ?? 0) ?></strong><small>پرداخت‌های ثبت‌شده در دفترکل</small></div></article>
    <article class="proma-accounting-kpi"><span class="proma-accounting-kpi-icon is-green"><i data-feather="download"></i></span><div><span class="proma-accounting-kpi-label">دریافت‌شده از کاربر</span><strong><?= money_toman($accountSummary['received_from_user'] ?? 0) ?></strong><small>دریافت‌های ثبت‌شده در دفترکل</small></div></article>
  </div>

  <section class="proma-accounting-panel">
    <div class="proma-accounting-section-heading"><div><span class="proma-accounting-section-icon is-purple"><i data-feather="edit-3"></i></span><div><h3>ثبت سند حسابداری</h3><p>مبلغ و اثر عملیات قبل از ارسال به سرور محاسبه و نمایش داده می‌شود.</p></div></div></div>
    <form method="post" action="<?= e(url('plugin/accounting/ledger/post')) ?>" class="proma-accounting-form-grid" data-accounting-ledger-form data-balance="<?= $currentBalance ?>" data-accounting-confirm data-confirm-title="تأیید ثبت سند" data-confirm-person="<?= e($accountUser['full_name'] ?? '') ?>" data-confirm-operation="ثبت سند جدید" data-confirm-effect="مانده قبل و بعد در پیش‌نمایش صفحه نمایش داده شده است">
      <?= csrf_field() ?><input type="hidden" name="user_id" value="<?= (int) ($accountUser['id'] ?? 0) ?>"><input type="hidden" name="operation_key" value="manual:<?= e(bin2hex(random_bytes(16))) ?>">
      <div class="proma-accounting-field span-4"><label class="proma-accounting-label" for="ledger-type">نوع سند <span class="proma-required">*</span></label><div class="proma-accounting-control"><select id="ledger-type" name="entry_type" required><?php foreach (['bonus' => ['پاداش','increase'], 'expense' => ['هزینه قابل پرداخت','increase'], 'deduction' => ['کسورات','decrease'], 'payment' => ['پرداخت وجه به کاربر','decrease'], 'receipt' => ['دریافت وجه از کاربر','increase'], 'manual_increase' => ['افزایش دستی','increase'], 'manual_decrease' => ['کاهش دستی','decrease']] as $value => $meta): ?><option value="<?= e($value) ?>" data-direction="<?= e($meta[1]) ?>"<?= $requestedAction === $value ? ' selected' : '' ?>><?= e($meta[0]) ?></option><?php endforeach; ?></select></div></div>
      <div class="proma-accounting-field span-4"><label class="proma-accounting-label" for="ledger-amount">مبلغ <span class="proma-required">*</span></label><div class="proma-accounting-control proma-accounting-input-group"><input id="ledger-amount" name="amount" inputmode="numeric" required data-accounting-money-input><span>تومان</span></div></div>
      <div class="proma-accounting-field span-4"><label class="proma-accounting-label" for="ledger-method">روش پرداخت یا دریافت</label><div class="proma-accounting-control"><input id="ledger-method" name="method" placeholder="نقدی، کارت یا حواله"></div></div>
      <div class="proma-accounting-field span-4"><label class="proma-accounting-label" for="ledger-tracking">شماره پیگیری</label><div class="proma-accounting-control"><input id="ledger-tracking" name="tracking" dir="ltr"></div></div>
      <div class="proma-accounting-field span-8"><label class="proma-accounting-label" for="ledger-description">شرح عملیات <span class="proma-required">*</span></label><div class="proma-accounting-control"><input id="ledger-description" name="description" required placeholder="شرح روشن و قابل پیگیری برای سند"></div></div>
      <div class="span-12 proma-accounting-ledger-preview" aria-live="polite"><div><span>مانده قبل</span><strong><?= money_toman($currentBalance) ?></strong></div><div><span>نوع اثر</span><strong data-ledger-effect>افزایش مانده</strong></div><div><span>مبلغ</span><strong data-ledger-amount>+ ۰ تومان</strong></div><div><span>مانده بعد</span><strong data-ledger-after><?= money_toman($currentBalance) ?></strong></div></div>
      <div class="span-12 proma-accounting-form-actions"><button class="btn btn-primary" type="submit"><i data-feather="check-circle"></i><span>بررسی و ثبت سند</span></button></div>
    </form>
  </section>

  <section class="proma-accounting-panel"><div class="proma-accounting-section-heading"><div><span class="proma-accounting-section-icon"><i data-feather="list"></i></span><div><h3>گردش حساب</h3><p>اصلاح سوابق فقط با سند معکوس و ثبت علت انجام می‌شود.</p></div></div></div>
    <?php if (!empty($entries)): ?><div class="proma-accounting-table-shell is-card-mobile"><table class="proma-accounting-table"><thead><tr><th>تراکنش</th><th>تاریخ</th><th>عملیات</th><th>اثر مالی</th><th>مانده بعد</th><th>شرح</th><th>عملیات</th></tr></thead><tbody><?php foreach ($entries as $entry): ?><tr><td dir="ltr"><?= e($entry['entry_number'] ?? '-') ?></td><td data-label="تاریخ"><?= e(jdatetime($entry['created_at'])) ?></td><td data-label="عملیات"><?= e(pa_entry_type_label($entry['entry_type'] ?? '')) ?></td><td data-label="اثر مالی"><?= pa_money_effect($entry['amount'], $entry['direction']) ?></td><td data-label="مانده بعد"><?= pa_balance($entry['balance_after']) ?></td><td data-label="شرح"><?= e($entry['description']) ?></td><td><?php if (($entry['entry_type'] ?? '') !== 'reversal' && empty($entry['reversed_entry_id'])): ?><form method="post" action="<?= e(url('plugin/accounting/ledger/reverse/' . (int) $entry['id'])) ?>" data-accounting-confirm data-confirm-title="ثبت سند معکوس" data-confirm-description="سند اصلی حذف نمی‌شود و یک سند معکوس برای حفظ تاریخچه ثبت خواهد شد." data-confirm-person="<?= e($accountUser['full_name'] ?? '') ?>" data-confirm-operation="معکوس‌سازی <?= e(pa_entry_type_label($entry['entry_type'] ?? '')) ?>" data-confirm-amount="<?= e(money_toman($entry['amount'])) ?>" data-confirm-effect="<?= ($entry['direction'] ?? '') === 'increase' ? 'کاهش مانده به اندازه مبلغ سند' : 'افزایش مانده به اندازه مبلغ سند' ?>" data-confirm-reason-required="1"><?= csrf_field() ?><button class="proma-accounting-icon-button is-danger" type="submit" aria-label="ثبت سند معکوس" title="ثبت سند معکوس"><i data-feather="rotate-ccw"></i></button></form><?php else: ?><?= pa_status('reversed') ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
      <div class="proma-accounting-mobile-list"><?php foreach ($entries as $entry): ?><article class="proma-accounting-data-card"><div class="proma-accounting-data-card-header"><div><strong><?= e(pa_entry_type_label($entry['entry_type'] ?? '')) ?></strong><small><?= e(jdatetime($entry['created_at'])) ?></small></div><?= pa_money_effect($entry['amount'], $entry['direction'], false) ?></div><div class="proma-accounting-data-card-grid"><div><span>شماره سند</span><strong dir="ltr"><?= e($entry['entry_number'] ?? '-') ?></strong></div><div><span>مانده بعد</span><strong><?= money_toman($entry['balance_after']) ?></strong></div><div><span>شرح</span><strong><?= e($entry['description']) ?></strong></div></div></article><?php endforeach; ?></div>
      <?= render_pagination($pagination ?? [], static function ($page) use ($accountUser) { return url('plugin/accounting/ledger/' . (int) ($accountUser['id'] ?? 0), ['page' => $page]); }) ?>
    <?php else: ?><?= pa_empty_state('هنوز تراکنشی ثبت نشده است', 'اولین سند را از فرم بالای صفحه ثبت کنید تا گردش حساب ساخته شود.', 'book-open') ?><?php endif; ?>
  </section>
  <?php pa_financial_dialog(); ?>
</div>
