<?php $currentBalance = (int) ($balance ?? 0); ?>
<div class="proma-accounting proma-accounting-ledger">
  <header class="proma-accounting-page-header"><div><span class="proma-accounting-eyebrow">دفترکل کاربر</span><h2><?= e($accountUser['full_name'] ?? '') ?></h2><p>مانده فعلی: <strong><?= money_toman($currentBalance) ?></strong></p></div><a class="btn btn-light" href="<?= e(url('plugin/accounting/help', ['section' => 'ledger'])) ?>"><i data-feather="help-circle"></i><span>راهنمای دفترکل</span></a></header>
  <section class="proma-accounting-balance-guide"><h3>قاعده اثر عملیات</h3><div><strong>پرداخت وجه به شخص</strong><span>کاهش مانده</span></div><div><strong>دریافت وجه از شخص</strong><span>افزایش مانده</span></div></section>
  <section class="proma-accounting-panel">
    <div class="proma-accounting-section-heading"><div><span class="proma-accounting-section-icon is-green"><i data-feather="edit-3"></i></span><div><h3>ثبت سند حسابداری</h3><p>پیش از تأیید، مانده قبل و بعد را بررسی کنید.</p></div></div></div>
    <form method="post" action="<?= e(url('plugin/accounting/ledger/post')) ?>" class="proma-accounting-form-grid" data-accounting-ledger-form data-balance="<?= $currentBalance ?>">
      <?= csrf_field() ?><input type="hidden" name="user_id" value="<?= (int) ($accountUser['id'] ?? 0) ?>"><input type="hidden" name="operation_key" value="manual:<?= e(bin2hex(random_bytes(16))) ?>">
      <div class="proma-accounting-field span-4"><label class="proma-accounting-label" for="ledger-type">نوع سند <span class="proma-required">*</span></label><div class="proma-accounting-control"><select id="ledger-type" name="entry_type" required><option value="bonus" data-direction="increase">پاداش</option><option value="expense" data-direction="increase">هزینه قابل پرداخت</option><option value="deduction" data-direction="decrease">کسر از حساب</option><option value="payment" data-direction="decrease">پرداخت وجه به کاربر</option><option value="receipt" data-direction="increase">دریافت وجه از کاربر</option><option value="manual_increase" data-direction="increase">افزایش دستی</option><option value="manual_decrease" data-direction="decrease">کاهش دستی</option></select></div></div>
      <div class="proma-accounting-field span-4"><label class="proma-accounting-label" for="ledger-amount">مبلغ <span class="proma-required">*</span></label><div class="proma-accounting-control proma-accounting-input-group"><input id="ledger-amount" name="amount" inputmode="numeric" required><span>تومان</span></div></div>
      <div class="proma-accounting-field span-4"><label class="proma-accounting-label" for="ledger-method">روش پرداخت یا دریافت</label><div class="proma-accounting-control"><input id="ledger-method" name="method" placeholder="نقدی، کارت یا حواله"></div></div>
      <div class="proma-accounting-field span-4"><label class="proma-accounting-label" for="ledger-tracking">شماره پیگیری</label><div class="proma-accounting-control"><input id="ledger-tracking" name="tracking" dir="ltr"></div></div>
      <div class="proma-accounting-field span-8"><label class="proma-accounting-label" for="ledger-description">شرح عملیات <span class="proma-required">*</span></label><div class="proma-accounting-control"><input id="ledger-description" name="description" required></div></div>
      <div class="span-12 proma-accounting-ledger-preview" aria-live="polite"><div><span>مانده قبل</span><strong><?= money_toman($currentBalance) ?></strong></div><div><span>نوع اثر</span><strong data-ledger-effect>افزایش مانده</strong></div><div><span>مبلغ</span><strong data-ledger-amount>۰ تومان</strong></div><div><span>مانده بعد</span><strong data-ledger-after><?= money_toman($currentBalance) ?></strong></div></div>
      <div class="span-12 proma-accounting-form-actions"><button class="btn btn-primary" type="submit"><i data-feather="check-circle"></i><span>بررسی و ثبت سند</span></button></div>
    </form>
  </section>
  <section class="proma-accounting-panel"><div class="proma-accounting-section-heading"><div><span class="proma-accounting-section-icon"><i data-feather="book-open"></i></span><div><h3>گردش حساب</h3><p>اسناد تاریخی فقط با سند معکوس اصلاح می‌شوند.</p></div></div></div><div class="table-responsive"><table class="table proma-accounting-table"><thead><tr><th>شماره</th><th>تاریخ</th><th>نوع</th><th>اثر بر مانده</th><th>مبلغ</th><th>مانده قبل</th><th>مانده بعد</th><th>شرح</th><th>عملیات</th></tr></thead><tbody><?php foreach (($entries ?? []) as $entry): ?><tr><td dir="ltr"><?= e($entry['entry_number'] ?? '-') ?></td><td><?= e(jdatetime($entry['created_at'])) ?></td><td><?= e($entry['entry_type']) ?></td><td class="<?= $entry['direction'] === 'increase' ? 'proma-accounting-positive' : 'proma-accounting-negative' ?>"><?= $entry['direction'] === 'increase' ? 'افزایش مانده' : 'کاهش مانده' ?></td><td><?= money_toman($entry['amount']) ?></td><td><?= money_toman($entry['balance_before']) ?></td><td><strong><?= money_toman($entry['balance_after']) ?></strong></td><td><?= e($entry['description']) ?></td><td><?php if (($entry['entry_type'] ?? '') !== 'reversal' && empty($entry['reversed_entry_id'])): ?><form method="post" action="<?= e(url('plugin/accounting/ledger/reverse/' . (int) $entry['id'])) ?>" class="proma-accounting-inline-action accounting-reverse-form" data-accounting-confirm="برای این سند، سند معکوس ثبت شود؟"><?= csrf_field() ?><div class="proma-accounting-control"><input name="reason" required placeholder="علت اصلاح"></div><button class="btn btn-sm btn-light" type="submit"><i data-feather="rotate-ccw"></i><span>ثبت معکوس</span></button></form><?php else: ?><span class="proma-accounting-status">اصلاح‌شده</span><?php endif; ?></td></tr><?php endforeach; ?><?php if (empty($entries)): ?><tr><td colspan="9" class="empty">هنوز سندی ثبت نشده است.</td></tr><?php endif; ?></tbody></table></div><?= render_pagination($pagination ?? [], static function ($page) use ($accountUser) { return url('plugin/accounting/ledger/' . (int) ($accountUser['id'] ?? 0), ['page' => $page]); }) ?></section>
</div>
