<?php
$settings = $settings ?? [];
$step = max(1, min(10, (int) ($step ?? 1)));
$steps = ['نوع کمیسیون', 'مقدار پیش‌فرض', 'مبنای محاسبه', 'حداقل و حداکثر', 'گرد کردن', 'زمان شناسایی', 'تأیید مدیر', 'ثبت خودکار', 'نمونه محاسبه', 'فعال‌سازی'];
$basisLabels = ['principal_amount' => 'مبلغ کل قرارداد', 'financed_amount' => 'مبلغ تأمین مالی‌شده', 'profit_amount' => 'سود قرارداد', 'collected_amount' => 'مبلغ وصول‌شده'];
$timingLabels = ['at_contract_creation' => 'هنگام ایجاد قرارداد', 'after_down_payment' => 'پس از دریافت پیش‌پرداخت', 'after_first_installment' => 'پس از پرداخت اولین قسط', 'after_full_settlement' => 'پس از تسویه کامل قرارداد', 'manual_approval' => 'با تأیید دستی مدیر'];
?>
<div class="proma-accounting proma-accounting-setup">
  <header class="proma-accounting-page-header"><div><span class="proma-accounting-eyebrow">راه‌اندازی اولیه</span><h2>راه‌اندازی حسابداری</h2><p>مرحله <?= to_persian_digits($step) ?> از ۱۰؛ پیشرفت هر مرحله ذخیره می‌شود.</p></div><form method="post" action="<?= e(url('plugin/accounting/setup/skip')) ?>" data-accounting-confirm="راه‌اندازی فعلاً رد شود؟"><?= csrf_field() ?><button class="btn btn-light" type="submit">رد کردن فعلاً</button></form></header>

  <div class="proma-accounting-setup-progress" role="progressbar" aria-valuemin="1" aria-valuemax="10" aria-valuenow="<?= $step ?>"><span style="width:<?= $step * 10 ?>%"></span></div>
  <ol class="proma-accounting-step-list"><?php foreach ($steps as $index => $label): ?><li class="<?= $index + 1 < $step ? 'is-done' : ($index + 1 === $step ? 'is-active' : '') ?>"><span><?= to_persian_digits($index + 1) ?></span><small><?= e($label) ?></small></li><?php endforeach; ?></ol>

  <section class="proma-accounting-panel proma-accounting-setup-panel">
    <form method="post" action="<?= e(url('plugin/accounting/setup/save')) ?>" class="proma-accounting-form-grid">
      <?= csrf_field() ?><input type="hidden" name="step" value="<?= $step ?>">
      <?php if ($step === 1): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>نوع پیش‌فرض کمیسیون</h3><p>قانون عمومی فقط وقتی استفاده می‌شود که فروشنده قانون اختصاصی نداشته باشد.</p></div>
        <div class="span-12 proma-accounting-choice-grid"><label><input type="radio" name="default_commission_type" value="percentage"<?= ($settings['default_commission_type'] ?? 'percentage') === 'percentage' ? ' checked' : '' ?>><span><i data-feather="percent"></i><strong>درصدی</strong><small>درصدی از مبنای انتخاب‌شده</small></span></label><label><input type="radio" name="default_commission_type" value="fixed"<?= ($settings['default_commission_type'] ?? '') === 'fixed' ? ' checked' : '' ?>><span><i data-feather="credit-card"></i><strong>مبلغ ثابت</strong><small>مبلغ یکسان برای هر فروش</small></span></label></div>
      <?php elseif ($step === 2): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>مقدار پیش‌فرض</h3><p>واحد بر اساس نوع انتخاب‌شده در مرحله قبل است.</p></div>
        <div class="proma-accounting-field span-6"><label class="proma-accounting-label" for="setup-value">مقدار پیش‌فرض کمیسیون</label><div class="proma-accounting-control proma-accounting-input-group"><input id="setup-value" name="default_commission_value" value="<?= e($settings['default_commission_value'] ?? '0') ?>" required inputmode="decimal"><span><?= ($settings['default_commission_type'] ?? 'percentage') === 'percentage' ? 'درصد' : 'تومان' ?></span></div></div>
      <?php elseif ($step === 3): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>مبنای محاسبه</h3><p>مبلغی که نرخ یا مبلغ کمیسیون نسبت به آن تفسیر می‌شود.</p></div>
        <div class="proma-accounting-field span-8"><label class="proma-accounting-label" for="setup-basis">مبنای پیش‌فرض محاسبه کمیسیون</label><div class="proma-accounting-control"><select id="setup-basis" name="default_calculation_basis"><?php foreach ($basisLabels as $value => $label): ?><option value="<?= e($value) ?>"<?= ($settings['default_calculation_basis'] ?? 'financed_amount') === $value ? ' selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="proma-accounting-help">تأمین مالی‌شده یعنی مبلغ قرارداد پس از کسر پیش‌پرداخت.</div></div>
      <?php elseif ($step === 4): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>حداقل و حداکثر</h3><p>این دو محدودیت اختیاری هستند و صفر به‌تنهایی معنای فعال‌بودن ندارد.</p></div>
        <div class="proma-accounting-field span-6"><label class="proma-accounting-switch-row"><input type="checkbox" name="minimum_commission_enabled" value="1"<?= ($settings['minimum_commission_enabled'] ?? '0') === '1' ? ' checked' : '' ?>><span class="proma-accounting-switch"></span><span><strong>اعمال حداقل کمیسیون</strong><small>کف مبلغ هر فروش</small></span></label><div class="proma-accounting-control proma-accounting-input-group"><input name="minimum_commission" value="<?= e($settings['minimum_commission'] ?? '0') ?>" inputmode="numeric"><span>تومان</span></div></div>
        <div class="proma-accounting-field span-6"><label class="proma-accounting-switch-row"><input type="checkbox" name="maximum_commission_enabled" value="1"<?= ($settings['maximum_commission_enabled'] ?? '0') === '1' ? ' checked' : '' ?>><span class="proma-accounting-switch"></span><span><strong>اعمال حداکثر کمیسیون</strong><small>سقف مبلغ هر فروش</small></span></label><div class="proma-accounting-control proma-accounting-input-group"><input name="maximum_commission" value="<?= e($settings['maximum_commission'] ?? '0') ?>" inputmode="numeric"><span>تومان</span></div></div>
      <?php elseif ($step === 5): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>گرد کردن مبلغ</h3><p>گرد کردن پس از محدودیت‌ها و با محاسبات صحیح integer انجام می‌شود.</p></div>
        <div class="proma-accounting-field span-6"><label class="proma-accounting-label" for="setup-round-method">روش گرد کردن</label><div class="proma-accounting-control"><select id="setup-round-method" name="rounding_method"><option value="none">بدون گرد کردن</option><option value="nearest"<?= ($settings['rounding_method'] ?? '') === 'nearest' ? ' selected' : '' ?>>نزدیک‌ترین مقدار</option><option value="down"<?= ($settings['rounding_method'] ?? '') === 'down' ? ' selected' : '' ?>>رو به پایین</option><option value="up"<?= ($settings['rounding_method'] ?? '') === 'up' ? ' selected' : '' ?>>رو به بالا</option></select></div></div>
        <div class="proma-accounting-field span-6"><label class="proma-accounting-label" for="setup-round-unit">واحد گرد کردن</label><div class="proma-accounting-control"><select id="setup-round-unit" name="rounding_unit"><?php foreach ([100,500,1000,5000,10000] as $unit): ?><option value="<?= $unit ?>"<?= (int) ($settings['rounding_unit'] ?? 1000) === $unit ? ' selected' : '' ?>><?= number_format($unit) ?> تومان</option><?php endforeach; ?></select></div></div>
      <?php elseif ($step === 6): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>زمان شناسایی کمیسیون</h3><p>تعیین می‌کند کمیسیون در کدام رویداد مالی ساخته یا به‌روزرسانی شود.</p></div>
        <div class="proma-accounting-field span-8"><label class="proma-accounting-label" for="setup-timing">زمان شناسایی</label><div class="proma-accounting-control"><select id="setup-timing" name="default_calculation_timing"><?php foreach ($timingLabels as $value => $label): ?><option value="<?= e($value) ?>"<?= ($settings['default_calculation_timing'] ?? 'at_contract_creation') === $value ? ' selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div></div>
      <?php elseif ($step === 7): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>تأیید کمیسیون</h3><p>در صورت فعال‌بودن، کمیسیون تا تأیید مدیر وارد مانده حساب نمی‌شود.</p></div>
        <div class="proma-accounting-field span-12"><label class="proma-accounting-switch-row"><input type="checkbox" name="require_commission_approval" value="1"<?= ($settings['require_commission_approval'] ?? '0') === '1' ? ' checked' : '' ?>><span class="proma-accounting-switch"></span><span><strong>کمیسیون قبل از ثبت در حساب نیاز به تأیید مدیر داشته باشد</strong><small>وضعیت اولیه «در انتظار تأیید» خواهد بود.</small></span></label></div>
      <?php elseif ($step === 8): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>ثبت خودکار در حساب</h3><p>ثبت خودکار با کلید idempotency انجام می‌شود و یک کمیسیون دوبار ثبت نخواهد شد.</p></div>
        <div class="proma-accounting-field span-12"><label class="proma-accounting-switch-row"><input type="checkbox" name="automatic_ledger_posting" value="1"<?= ($settings['automatic_ledger_posting'] ?? '0') === '1' ? ' checked' : '' ?>><span class="proma-accounting-switch"></span><span><strong>پس از تأیید، کمیسیون خودکار در حساب کاربر ثبت شود</strong><small>یک تراکنش افزایشی در گردش حساب ایجاد می‌شود.</small></span></label></div>
      <?php elseif ($step === 9): ?>
        <div class="span-12 proma-accounting-step-copy"><h3>بررسی نمونه محاسبه</h3><p>نمونه بر اساس قرارداد ۲۰ میلیون تومانی و تأمین مالی ۱۵ میلیون تومان است.</p></div>
        <div class="span-12 proma-accounting-breakdown"><div><span>قانون</span><strong><?= e($preview['rule_name'] ?? '-') ?></strong></div><div><span>مبلغ مبنا</span><strong><?= money_toman($preview['basis_amount'] ?? 0) ?></strong></div><div><span>کمیسیون اولیه</span><strong><?= money_toman($preview['raw_commission'] ?? 0) ?></strong></div><div class="is-final"><span>کمیسیون نهایی</span><strong><?= money_toman($preview['final_commission'] ?? 0) ?></strong></div></div>
      <?php else: ?>
        <div class="span-12 proma-accounting-step-copy"><h3>ذخیره و فعال‌سازی</h3><p>تنظیمات آماده است. فعال‌سازی هیچ کمیسیون یا سند تاریخی را تغییر نمی‌دهد.</p></div>
        <dl class="span-12 proma-accounting-review-list"><div><dt>نوع</dt><dd><?= ($settings['default_commission_type'] ?? 'percentage') === 'percentage' ? 'درصدی' : 'مبلغ ثابت' ?></dd></div><div><dt>مقدار</dt><dd><?= e($settings['default_commission_value'] ?? '0') ?></dd></div><div><dt>مبنا</dt><dd><?= e($basisLabels[$settings['default_calculation_basis'] ?? 'financed_amount'] ?? '-') ?></dd></div><div><dt>زمان</dt><dd><?= e($timingLabels[$settings['default_calculation_timing'] ?? 'at_contract_creation'] ?? '-') ?></dd></div></dl>
      <?php endif; ?>
      <div class="span-12 proma-accounting-setup-actions"><?php if ($step > 1): ?><a class="btn btn-light" href="<?= e(url('plugin/accounting/setup', ['step' => $step - 1])) ?>"><i data-feather="arrow-right"></i><span>مرحله قبل</span></a><?php else: ?><span></span><?php endif; ?><button class="btn btn-primary" type="submit"><span><?= $step === 10 ? 'ذخیره و فعال‌سازی' : 'ذخیره و مرحله بعد' ?></span><i data-feather="arrow-left"></i></button></div>
    </form>
  </section>
</div>
