<?php
$sections=['overview'=>'نمای کلی','ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بازوهای بله','telegram'=>'ربات تلگرام','otp'=>'ورود با کد یکبار مصرف','mfa'=>'احراز هویت دومرحله‌ای','otp-security'=>'محدودیت‌ها و امنیت OTP','signature'=>'تنظیمات امضا','signers'=>'امضاکنندگان','hashes'=>'هش‌ها و یکپارچگی','document-versions'=>'نسخه‌های اسناد','evidence-retention'=>'سیاست نگهداری شواهد','events'=>'رویدادهای قابل اطلاع‌رسانی','notifications'=>'قوانین ارسال اعلان','compose'=>'ارسال پیام عمومی','variables'=>'رجیستری متغیرها','templates'=>'قالب‌های پیام','deliveries'=>'گزارش تحویل','health'=>'سلامت افزونه','retention'=>'نگهداری داده‌ها','audit'=>'گزارش Audit'];
$ruleMap=[];foreach($rules as$r)$ruleMap[$r['event_key']]=$r;
$eventByKey=[];foreach($events as$eventRow)$eventByKey[$eventRow['event_key']]=$eventRow;
$navGroups=[
  'تنظیمات اصلی'=>['overview'],
  'ارائه‌دهندگان ارتباطی'=>['ippanel','smsir','bale','telegram'],
  'احراز هویت'=>['otp','mfa','otp-security'],
  'امضای الکترونیکی'=>['signature','signers','hashes','document-versions','evidence-retention'],
  'اعلان‌ها'=>['events','notifications','compose','variables','templates'],
  'مدیریت و نگهداری'=>['deliveries','health','retention','audit'],
];
?>
<div class="grid proma-settings-shell">
  <nav class="proma-settings-tabs" aria-label="تنظیمات امضا و ارتباطات">
    <div class="proma-settings-version"><div><strong>امضا و ارتباطات پروما</strong><small>مدیریت کانال‌ها، OTP و امضای قرارداد</small></div><span class="badge badge-light-success">فعال</span></div>
    <?php foreach($navGroups as$group=>$keys):?><div class="proma-settings-tab-group"><span><?=e($group)?></span><div>
      <?php foreach($keys as$key):?><a class="tab-link <?=$section===$key?'active':''?>" href="<?=e(url('plugin/sign-connect/settings/'.$key))?>"><?=e($sections[$key])?></a><?php endforeach;?>
    </div></div><?php endforeach;?>
  </nav>

  <section class="card proma-settings-panel active">
    <div class="card-header"><div><h2><?=e($sections[$section])?></h2><small>تنظیمات این بخش مستقل ذخیره می‌شود.</small></div></div>
    <div class="card-body">
      <?php if(!empty($loadError)):?><div class="notice danger"><?=e($loadError)?></div><?php endif;?>
      <?php if($section==='overview'):?>
        <div class="form-grid four">
          <div class="notice info"><strong><?=e(to_persian_digits($counts['requests']))?></strong><br>درخواست امضا</div>
          <div class="notice success"><strong><?=e(to_persian_digits($counts['signed']))?></strong><br>امضای تکمیل‌شده</div>
          <div class="notice warning"><strong><?=e(to_persian_digits($counts['queued']))?></strong><br>پیام در صف</div>
          <div class="notice <?= $counts['dead']?'danger':'success' ?>"><strong><?=e(to_persian_digits($counts['dead']))?></strong><br>ارسال ناموفق</div>
        </div>
        <div class="table-wrap mt-3"><table><thead><tr><th>ارائه‌دهنده</th><th>وضعیت</th><th>توضیح</th><th>تنظیمات</th></tr></thead><tbody>
          <?php foreach(['ippanel'=>['IPPanel','ippanel'],'smsir'=>['SMS.ir','smsir'],'bale'=>['بله سفیر','bale'],'telegram'=>['تلگرام','telegram'],'in_app'=>['داخل سامانه','notifications']] as$key=>$item):$enabled=($settings['provider_'.$key.'_enabled']??'0')==='1';?>
          <tr><td><strong><?=e($item[0])?></strong></td><td><span class="badge <?=$enabled?'badge-light-success':'badge-light-secondary'?>"><?=$enabled?'فعال':'غیرفعال'?></span></td><td><?=$enabled?'قابل استفاده در قوانین ارسال':'تنظیمات و سوابق حفظ شده است'?></td><td><a class="btn small secondary" href="<?=e(url('plugin/sign-connect/settings/'.$item[1]))?>">مدیریت</a></td></tr>
          <?php endforeach;?>
        </tbody></table></div>

      <?php elseif(in_array($section,['ippanel','smsir'],true)): $provider=$section; $isIp=$provider==='ippanel';?>
        <form method="post" action="<?=e(url('plugin/sign-connect/settings/save'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="<?=e($provider)?>">
          <div class="notice info">کلید ذخیره‌شده هرگز در HTML نمایش داده نمی‌شود. تست اتصال فقط با اقدام صریح انجام می‌شود.</div>
          <div class="form-grid two mt-3">
            <label>وضعیت <?=e($isIp?'IPPanel':'SMS.ir')?><select name="provider_<?=e($provider)?>_enabled"><option value="0">غیرفعال</option><option value="1"<?=($settings['provider_'.$provider.'_enabled']??'0')==='1'?' selected':''?>>فعال</option></select></label>
            <label>کلید جدید<input name="<?=e($provider)?>_api_key" type="password" autocomplete="new-password" placeholder="<?=!empty($settings[$provider.'_api_key'])?'ذخیره شده است':'کلید را وارد کنید'?>"></label>
            <label><?=e($isIp?'سرشماره / Originator':'خط ارسال')?><input name="<?=e($isIp?'ippanel_from_number':'smsir_sender_line')?>" dir="ltr" value="<?=e($settings[$isIp?'ippanel_from_number':'smsir_sender_line']??'')?>"></label>
            <label>مهلت اتصال (ثانیه)<input type="number" min="2" max="10" name="<?=e($provider)?>_connect_timeout" value="<?=e($settings[$provider.'_connect_timeout']??'5')?>"></label>
            <label>مهلت کل پاسخ<input type="number" min="3" max="30" name="<?=e($provider)?>_timeout" value="<?=e($settings[$provider.'_timeout']??'10')?>"></label>
            <label>تعداد تلاش مجدد<input type="number" min="0" max="5" name="<?=e($provider)?>_retry_count" value="<?=e($settings[$provider.'_retry_count']??'3')?>"></label>
          </div>
          <?php $selectedCaps=\Proma\Plugins\SignConnect\Services\ProviderCapabilityCatalog::normalize($provider,$settings['provider_'.$provider.'_capabilities']??'');?>
          <div class="psc-capability-groups mt-3"><?php foreach(\Proma\Plugins\SignConnect\Services\ProviderCapabilityCatalog::grouped($provider) as$groupTitle=>$caps):?><fieldset><legend><?=e($groupTitle)?></legend><div class="psc-capability-cards"><?php foreach($caps as$capKey=>$capTitle):?><label class="psc-capability-card"><input type="checkbox" name="capabilities[]" value="<?=e($capKey)?>"<?=in_array($capKey,$selectedCaps,true)?' checked':''?>><span><strong><?=e($capTitle)?></strong><small>این قابلیت فقط پس از فعال‌سازی در ارسال‌ها استفاده می‌شود.</small></span></label><?php endforeach;?></div></fieldset><?php endforeach;?></div>
          <div class="actions mt-3"><button class="btn" type="submit">ذخیره تنظیمات و قابلیت‌ها</button></div>
        </form>
        <details class="psc-test-panel mt-3"><summary>تست ارسال <?=e($isIp?'IPPanel':'SMS.ir')?></summary><form method="post" action="<?=e(url('plugin/sign-connect/provider/'.$provider.'/test'))?>"><?=csrf_field()?><div class="notice info">این عملیات فقط با کلیک شما یک پیام واقعی ارسال می‌کند و نتیجه را بدون ذخیره متن و شماره کامل ثبت می‌کند.</div><div class="form-grid two mt-3"><label>شماره موبایل آزمایشی<input name="test_mobile" placeholder="09xxxxxxxxx" inputmode="tel" required></label><label>نوع ارسال<select name="send_mode"><option value="text">پیام متنی عادی</option><option value="<?=$isIp?'pattern':'verify'?>"><?=$isIp?'پترن IPPanel':'Verify/Template SMS.ir'?></option></select></label><label>کد پترن / Template ID<input name="pattern" dir="ltr"></label><label>متغیرهای تست به‌صورت JSON<input name="variables" dir="ltr" value="{}"><small>نمونه: {&quot;otp&quot;:&quot;123456&quot;}</small></label><label class="full">متن آزمایشی<textarea name="test_message" rows="3" maxlength="500" required>این یک پیام آزمایشی از سامانه پرما پی است.</textarea></label></div><div class="actions"><button class="btn" type="submit">ارسال پیام آزمایشی</button></div></form></details>
        <hr><h3><?=e($isIp?'پترن‌های رویداد IPPanel':'قالب‌های Verify رویداد SMS.ir')?></h3>
        <form method="post" action="<?=e(url('plugin/sign-connect/provider/'.$provider.'/mappings/save'))?>"><?=csrf_field()?>
          <div class="table-wrap"><table><thead><tr><th>رویداد</th><th>نوع ارسال</th><th><?=e($isIp?'کد پترن':'Template ID')?></th><th>متغیرها</th><th>متن نمونه</th></tr></thead><tbody>
          <?php foreach($events as$ev):$m=$providerMappings[$ev['event_key']]??[];?><tr>
            <td><strong><?=e($ev['title_fa'])?></strong><small class="muted d-block" dir="ltr"><?=e($ev['event_key'])?></small></td>
            <td><select name="events[<?=e($ev['event_key'])?>][mode]"><?php foreach(($isIp?['disabled'=>'غیرفعال','text'=>'متن عادی','pattern'=>'پترن']:['disabled'=>'غیرفعال','text'=>'متن عادی','verify'=>'Verify/Template']) as$v=>$l):?><option value="<?=$v?>"<?=($m['send_mode']??'disabled')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></td>
            <td><input dir="ltr" name="events[<?=e($ev['event_key'])?>][external_template_id]" value="<?=e($m['external_template_id']??'')?>"></td>
            <td><input dir="ltr" name="events[<?=e($ev['event_key'])?>][variables]" value="<?=e(implode(',',json_decode($m['variable_mapping_json']??'[]',true)?:json_decode($ev['variables_json'],true)?:[]))?>"></td>
            <td><textarea name="events[<?=e($ev['event_key'])?>][body]" rows="3"><?=e($m['template_body']??$ev['default_text'])?></textarea><small><?=e($ev['sample_text'])?></small></td>
          </tr><?php endforeach;?></tbody></table></div><div class="actions mt-3"><button class="btn" type="submit">ذخیره نگاشت‌های رویداد</button></div>
        </form>

      <?php elseif($section==='bale'):?>
        <div class="notice warning">توکن فعلی هرگز نمایش داده نمی‌شود. خالی گذاشتن فیلد توکن در ویرایش، کلید ذخیره‌شده را حفظ می‌کند.</div>
        <?php $baleStatuses=['configured_not_verified'=>'نیازمند تست','verified'=>'تأییدشده','active'=>'فعال','disabled'=>'غیرفعال','test_failed'=>'آزمون ناموفق','degraded'=>'دارای اختلال','invalid_credentials'=>'اطلاعات اتصال نامعتبر','insufficient_credit'=>'اعتبار ناکافی'];?>
        <div class="psc-bot-grid mt-3"><?php foreach($baleAccounts as$a):$caps=json_decode($a['capabilities_json']??'{}',true)?:[];?><article class="psc-bot-card"><header><div><h3><?=e($a['title'])?></h3><small><?=e($a['environment'])?> · Bot ID: <b dir="ltr"><?=e($a['external_bot_id'])?></b></small></div><div class="actions"><span class="badge <?=!empty($a['is_active'])?'badge-light-success':'badge-light-secondary'?>"><?=e($baleStatuses[$a['status']]??$a['status'])?></span><?php if(!empty($a['is_default'])):?><span class="badge">پیش‌فرض</span><?php endif;?></div></header><dl><div><dt>توکن</dt><dd><?=!empty($a['secret_stored'])?'ذخیره‌شده':'ثبت‌نشده'?></dd></div><div><dt>قابلیت فعال</dt><dd><?=e(count(array_filter($caps)))?></dd></div><div><dt>رویداد مجاز</dt><dd><?=e($a['enabled_event_count']??0)?></dd></div><div><dt>آخرین تست</dt><dd><?=e($a['last_tested_at']?:'انجام نشده')?></dd></div><div><dt>آخرین ارسال موفق</dt><dd><?=e($a['last_success_at']?:'—')?></dd></div><div><dt>آخرین خطا</dt><dd><?=e($a['last_failure_at']?:'—')?></dd></div></dl><div class="psc-bot-actions"><a class="btn small secondary" href="<?=e(url('plugin/sign-connect/settings/bale',['edit'=>$a['id']]))?>" aria-label="ویرایش بازوی بله">ویرایش تنظیمات</a><a class="btn small secondary" href="<?=e(url('plugin/sign-connect/settings/bale',['edit'=>$a['id']]).'#bale-permissions')?>" aria-label="مدیریت دسترسی‌های ارسال">دسترسی‌ها</a><details><summary class="btn small secondary">تست ارسال</summary><form class="psc-popover-form" method="post" action="<?=e(url('plugin/sign-connect/bale/test/'.$a['id']))?>"><?=csrf_field()?><label>شماره آزمایشی<input name="test_mobile" placeholder="09xxxxxxxxx" required></label><label>نوع پیام<select name="message_type"><option value="text">متنی</option><option value="secure">رمزدار</option></select></label><label>متن آزمایشی<textarea name="test_message" maxlength="500" required>این یک پیام آزمایشی از سامانه پرما پی است.</textarea></label><button class="btn small">ارسال پیام آزمایشی</button></form></details><form method="post" action="<?=e(url('plugin/sign-connect/bale/state/'.$a['id']))?>"><?=csrf_field()?><button class="btn small <?=!empty($a['is_active'])?'danger':''?>" name="action" value="<?=!empty($a['is_active'])?'disable':'activate'?>"><?=!empty($a['is_active'])?'غیرفعال‌سازی':'فعال‌سازی بازو'?></button><button class="btn small secondary" name="action" value="default">انتخاب پیش‌فرض</button><button class="btn small danger" name="action" value="archive" onclick="return confirm('این بازو آرشیو شود؟')">آرشیو</button></form></div></article><?php endforeach;?><?php if(!$baleAccounts):?><div class="empty">هنوز بازوی بله ثبت نشده است.</div><?php endif;?></div>
        <?php $editCaps=json_decode($baleEdit['capabilities_json']??'{}',true)?:[];?>
        <form id="bale-editor" class="mt-3 psc-bot-editor" method="post" action="<?=e(url('plugin/sign-connect/bale/save'))?>"><?=csrf_field()?><?php if($baleEdit):?><input type="hidden" name="id" value="<?=e($baleEdit['id'])?>"><?php endif;?><div class="card-header card-no-border"><div><h3><?=$baleEdit?'ویرایش بازوی بله':'افزودن بازوی بله'?></h3><small><?=$baleEdit?'ویرایش اطلاعات، قابلیت‌ها و جایگزینی اختیاری توکن':'تعریف اتصال جدید'?></small></div></div><div class="form-grid two"><label>عنوان داخلی بازو<input name="title" value="<?=e($baleEdit['title']??'')?>" minlength="2" maxlength="120" required></label><label>شناسه عددی بازو<input name="bot_id" value="<?=e($baleEdit['external_bot_id']??'')?>" required inputmode="numeric" dir="ltr"></label><label class="full"><?=$baleEdit?'جایگزینی توکن وب‌سرویس':'توکن وب‌سرویس بله'?><input name="api_key" <?=$baleEdit?'':'required'?> type="password" autocomplete="new-password" dir="ltr"><small><?=$baleEdit?'در صورت عدم نیاز به تعویض، خالی بگذارید. تعویض توکن بازو را نیازمند تست مجدد می‌کند.':'پس از ذخیره مجدداً نمایش داده نمی‌شود.'?></small></label><div class="full psc-capability-groups"><?php foreach(\Proma\Plugins\SignConnect\Services\BaleCapabilityCatalog::all() as$group):?><fieldset><legend><?=e($group['title'])?></legend><div class="psc-capability-cards"><?php foreach($group['items'] as$key=>$cap):?><label class="psc-capability-card"><input type="checkbox" name="capabilities[<?=e($key)?>]" value="1"<?=!empty($editCaps[$key])?' checked':''?>><span><strong><?=e($cap[0])?></strong><small><?=e($cap[1])?></small><code dir="ltr"><?=e($key)?></code></span></label><?php endforeach;?></div></fieldset><?php endforeach;?></div></div><div class="psc-save actions"><button class="btn" type="submit">ذخیره تنظیمات بازو</button><?php if($baleEdit):?><a class="btn secondary" href="<?=e(url('plugin/sign-connect/settings/bale'))?>">انصراف از ویرایش</a><?php endif;?></div></form>
        <?php if($baleEdit):?><form id="bale-permissions" class="mt-3" method="post" action="<?=e(url('plugin/sign-connect/bale/permissions/'.$baleEdit['id']))?>"><?=csrf_field()?><div class="card-header card-no-border"><div><h3>دسترسی‌های ارسال رویداد</h3><small>این تنظیمات فقط برای «<?=e($baleEdit['title'])?>» اعمال می‌شود.</small></div></div><div class="psc-event-catalog"><?php foreach($eventGroups as$category=>$rows):?><details class="psc-event-group" open><summary><strong><?=e(\Proma\Plugins\SignConnect\Services\NotificationEventCatalog::CATEGORIES[$category]??$category)?></strong></summary><div class="psc-event-list"><?php foreach($rows as$ev):$permission=$baleEventPermissions[$ev['event_key']]??[];?><article class="psc-event-row"><div class="psc-event-copy"><strong><?=e($ev['title_fa'])?></strong><p><?=e($ev['description_fa'])?></p><code dir="ltr"><?=e($ev['event_key'])?></code></div><div class="psc-event-permission"><label><input type="checkbox" name="events[<?=e($ev['event_key'])?>][enabled]" value="1"<?=!empty($permission['is_enabled'])?' checked':''?>> مجاز</label><select name="events[<?=e($ev['event_key'])?>][mode]"><option value="text"<?=($permission['send_mode']??'text')==='text'?' selected':''?>>متن عادی</option><option value="secure"<?=($permission['send_mode']??'')==='secure'?' selected':''?>>رمزدار</option><option value="template"<?=($permission['send_mode']??'')==='template'?' selected':''?>>قالبی</option></select><input name="events[<?=e($ev['event_key'])?>][external_template_id]" value="<?=e($permission['external_template_id']??'')?>" placeholder="شناسه قالب"></div></article><?php endforeach;?></div></details><?php endforeach;?></div><div class="psc-save actions"><button class="btn">ذخیره دسترسی‌ها</button><span class="muted">تغییرات در یک تراکنش ذخیره می‌شوند.</span></div></form><?php endif;?>

      <?php elseif($section==='telegram'):?>
        <div class="form-grid two"><div class="notice <?=!empty($settings['telegram_bot_token'])?'success':'warning'?>">توکن: <?=!empty($settings['telegram_bot_token'])?'ذخیره شده است':'ثبت نشده'?></div><div class="notice info">Bot: <?=e($settings['telegram_bot_username']?'@'.$settings['telegram_bot_username']:'تعریف نشده')?> · ID: <?=e($settings['telegram_bot_id']?:'—')?></div></div>
        <form class="mt-3" method="post" action="<?=e(url('plugin/sign-connect/telegram/validate'))?>"><?=csrf_field()?><div class="notice info">ربات را در BotFather بسازید؛ افزونه توکن جدید را با getMe اعتبارسنجی می‌کند.</div><div class="form-grid mt-3"><label class="full">توکن جدید یا جایگزین<input type="password" name="bot_token" autocomplete="new-password" required dir="ltr"></label></div><div class="actions"><button class="btn" type="submit">اعتبارسنجی و ذخیره امن</button></div></form>
        <?php $selectedCaps=\Proma\Plugins\SignConnect\Services\ProviderCapabilityCatalog::normalize('telegram',$settings['provider_telegram_capabilities']??'');?>
        <form class="mt-3" method="post" action="<?=e(url('plugin/sign-connect/settings/save'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="telegram"><div class="form-grid two"><label>وضعیت ربات<select name="provider_telegram_enabled"><option value="0">غیرفعال</option><option value="1"<?=($settings['provider_telegram_enabled']??'0')==='1'?' selected':''?>>فعال</option></select></label><label>حالت قالب‌بندی<select name="telegram_parse_mode"><option value="HTML">HTML امن</option><option value="MarkdownV2"<?=($settings['telegram_parse_mode']??'HTML')==='MarkdownV2'?' selected':''?>>MarkdownV2</option></select></label></div><div class="psc-capability-groups mt-3"><?php foreach(\Proma\Plugins\SignConnect\Services\ProviderCapabilityCatalog::grouped('telegram') as$groupTitle=>$caps):?><fieldset><legend><?=e($groupTitle)?></legend><div class="psc-capability-cards"><?php foreach($caps as$capKey=>$capTitle):?><label class="psc-capability-card"><input type="checkbox" name="capabilities[]" value="<?=e($capKey)?>"<?=in_array($capKey,$selectedCaps,true)?' checked':''?>><span><strong><?=e($capTitle)?></strong><small>ارسال این نوع پیام از ربات مجاز باشد.</small></span></label><?php endforeach;?></div></fieldset><?php endforeach;?></div><div class="actions"><button class="btn">ذخیره وضعیت و قابلیت‌ها</button></div></form>
        <details class="psc-test-panel mt-3"><summary>تست ارسال تلگرام</summary><form method="post" action="<?=e(url('plugin/sign-connect/provider/telegram/test'))?>"><?=csrf_field()?><div class="notice info">فقط کاربری قابل انتخاب است که حساب تلگرام او قبلاً به سامانه متصل شده باشد.</div><div class="form-grid two mt-3"><label>شناسه کاربر سامانه<input name="test_user_id" type="number" min="1" required></label><label class="full">متن آزمایشی<textarea name="test_message" rows="3" maxlength="500" required>این یک پیام آزمایشی از سامانه پرما پی است.</textarea></label></div><input type="hidden" name="send_mode" value="text"><div class="actions"><button class="btn">ارسال پیام آزمایشی</button></div></form></details>
        <hr><h3>اتصال حساب تلگرام من</h3><p><?=$telegramLink?'تلگرام متصل است: @'.e($telegramLink['username']??'—'):'تلگرام متصل نیست.'?></p><?php if($generatedTelegramLink):?><div class="notice success"><span dir="ltr"><?=e($generatedTelegramLink['url'])?></span> <a class="btn small" href="<?=e($generatedTelegramLink['url'])?>" target="_blank" rel="noopener">بازکردن تلگرام</a></div><?php endif;?><div class="actions"><form method="post" action="<?=e(url('plugin/sign-connect/telegram/link'))?>"><?=csrf_field()?><button class="btn">ایجاد لینک یک‌بارمصرف</button></form><?php if($telegramLink):?><form method="post" action="<?=e(url('plugin/sign-connect/telegram/disconnect'))?>"><?=csrf_field()?><button class="btn danger">قطع اتصال</button></form><?php endif;?></div>

      <?php elseif($section==='compose'):?>
        <?php $registry=new \Proma\Plugins\SignConnect\Services\ProviderRegistry();$channelLabels=['in_app'=>'داخل سامانه','ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بله','telegram'=>'تلگرام'];?>
        <form method="post" action="<?=e(url('plugin/sign-connect/messages/send'))?>"><?=csrf_field()?>
          <div class="notice info">پیام‌ها ابتدا در صف امن سامانه ثبت می‌شوند. برای هر کانال فقط مخاطب مرتبط استفاده می‌شود و متن پیام در گزارش تحویل نمایش داده نمی‌شود.</div>
          <div class="form-grid two mt-3">
            <label>عنوان پیام<input name="title" maxlength="190" required placeholder="عنوان اعلان"></label>
            <label class="full">متن پیام<textarea name="message" rows="6" maxlength="2000" required placeholder="متن پیام عمومی"></textarea><small>حداکثر ۲۰۰۰ نویسه</small></label>
            <label>شماره‌های موبایل<textarea name="mobiles" rows="4" dir="ltr" placeholder="0912... هر شماره در یک خط"></textarea><small>برای IPPanel، SMS.ir و بله</small></label>
            <label>شناسه کاربران سامانه<textarea name="user_ids" rows="4" dir="ltr" placeholder="15, 28, 42"></textarea><small>برای اعلان داخل سامانه و حساب تلگرام متصل</small></label>
          </div>
          <fieldset class="mt-3"><legend>کانال‌های ارسال</legend><div class="psc-capability-cards"><?php foreach($channelLabels as$channel=>$label):try{$available=$registry->supports($channel,'custom_message')&&(($settings['provider_'.$channel.'_enabled']??'1')==='1'||$channel==='bale');}catch(\Throwable $e){$available=false;}?><label class="psc-capability-card <?=$available?'':'is-disabled'?>"><input type="checkbox" name="channels[]" value="<?=e($channel)?>"<?=$available?'':' disabled'?>> <span><strong><?=e($label)?></strong><small><?=$available?'قابلیت پیام عمومی فعال است.':'ابتدا قابلیت پیام عمومی را در تنظیمات این کانال فعال کنید.'?></small></span></label><?php endforeach;?></div></fieldset>
          <div class="notice warning mt-3">در هر نوبت حداکثر ۱۰۰ مخاطب پذیرفته می‌شود. ارسال خارجی به‌صورت صف‌بندی‌شده انجام می‌شود.</div>
          <div class="actions"><button class="btn" type="submit">قرار دادن پیام‌ها در صف ارسال</button></div>
        </form>

      <?php elseif($section==='notifications'):?>
        <?php $configuredRules=count($ruleMap);$enabledRules=count(array_filter($ruleMap,fn($x)=>!empty($x['is_enabled'])));$fallbackRules=count(array_filter($ruleMap,fn($x)=>in_array('fallback',json_decode($x['channels_json']??'{}',true)?:[],true)));?>
        <div class="psc-event-summary"><article><strong><?=e($configuredRules)?></strong><span>رویداد دارای قانون</span></article><article><strong><?=e(count($events)-$configuredRules)?></strong><span>بدون قانون</span></article><article><strong><?=e($enabledRules)?></strong><span>قانون فعال</span></article><article><strong><?=e($fallbackRules)?></strong><span>دارای جایگزین</span></article></div>
        <form method="post" action="<?=e(url('plugin/sign-connect/rules/save'))?>" data-rules-form><?=csrf_field()?><div class="notice info">تغییرها خودکار ارسال نمی‌شوند؛ پس از بررسی همه ردیف‌ها، یک‌جا ذخیره کنید.</div><div class="table-wrap mt-3 psc-rules-wrap"><table class="psc-rules-table"><thead><tr><th>رویداد</th><th>فعال</th><th>حساسیت</th><?php foreach(['داخل','IPPanel','SMS.ir','بله','تلگرام']as$l):?><th><?=$l?></th><?php endforeach;?></tr></thead><tbody><?php foreach($events as$eventRow):$event=$eventRow['event_key'];$r=$ruleMap[$event]??[];$chs=json_decode($r['channels_json']??'{}',true)?:[];?><tr><td><strong><?=e($eventRow['title_fa'])?></strong><small class="muted d-block" dir="ltr"><?=e($event)?></small><p class="psc-mobile-description"><?=e($eventRow['description_fa'])?></p></td><td data-label="فعال"><input type="checkbox" name="events[<?=e($event)?>][enabled]" value="1"<?=!empty($r['is_enabled'])?' checked':''?>></td><td data-label="حساسیت"><select name="events[<?=e($event)?>][sensitivity]"><?php foreach(['service'=>'خدماتی','financial'=>'مالی','confidential'=>'محرمانه','security'=>'امنیتی','legal'=>'حقوقی']as$v=>$l):?><option value="<?=$v?>"<?=($r['sensitivity']??$eventRow['sensitivity'])===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></td><?php foreach(['in_app'=>'داخل سامانه','ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بله','telegram'=>'تلگرام']as$c=>$channelLabel):?><td data-label="<?=e($channelLabel)?>"><select name="events[<?=e($event)?>][channels][<?=$c?>]"><?php foreach(['disabled'=>'خاموش','primary'=>'اصلی','fallback'=>'جایگزین','simultaneous'=>'هم‌زمان','linked_only'=>'فقط متصل']as$v=>$l):?><option value="<?=$v?>"<?=($chs[$c]??'disabled')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><div class="psc-save actions mt-3"><span class="muted" data-dirty-count>تغییری ذخیره‌نشده است.</span><button class="btn" type="submit">ذخیره همه قوانین تغییرکرده</button></div></form>

      <?php elseif($section==='otp'):?>
        <form method="post" action="<?=e(url('plugin/sign-connect/settings/save'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="otp"><div class="notice info">ورود با رمز فعلی مشتری حفظ می‌شود؛ OTP فقط روش موازی است و fallback همان challenge را ارسال می‌کند.</div><div class="form-grid two mt-3">
          <label>ورود با OTP<select name="otp_login_enabled"><option value="0">غیرفعال</option><option value="1"<?=($settings['otp_login_enabled']??'0')==='1'?' selected':''?>>فعال در کنار رمز</option></select></label>
          <label>طول کد<input name="otp_length" type="number" min="4" max="8" value="<?=e($settings['otp_length'])?>"></label>
          <label>اعتبار کد (ثانیه)<input name="otp_ttl_seconds" type="number" min="60" max="600" value="<?=e($settings['otp_ttl_seconds'])?>"></label>
          <label>فاصله ارسال مجدد<input name="otp_resend_seconds" type="number" min="30" max="3600" value="<?=e($settings['otp_resend_seconds'])?>"></label>
          <label>حداکثر تلاش اعتبارسنجی<input name="otp_max_attempts" type="number" min="3" max="10" value="<?=e($settings['otp_max_attempts'])?>"></label>
          <label>حد ارسال ساعتی<input name="otp_hourly_limit" type="number" min="1" max="30" value="<?=e($settings['otp_hourly_limit'])?>"></label>
          <label>ارائه‌دهنده اصلی<select name="otp_primary_provider"><?php foreach(['ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بله','telegram'=>'تلگرام','in_app'=>'داخل سامانه']as$v=>$l):?><option value="<?=$v?>"<?=($settings['otp_primary_provider']??'ippanel')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label>
          <label>ارائه‌دهنده جایگزین<select name="otp_fallback_provider"><?php foreach(['ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بله','telegram'=>'تلگرام','in_app'=>'داخل سامانه']as$v=>$l):?><option value="<?=$v?>"<?=($settings['otp_fallback_provider']??'smsir')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label>
          <label>حالت پیام<select name="otp_send_mode"><?php foreach(['default_text'=>'متن پیش‌فرض','custom_text'=>'قالب سفارشی','ippanel_pattern'=>'پترن IPPanel','smsir_verify'=>'Verify در SMS.ir','bale_otp'=>'OTP بله','telegram'=>'تلگرام متصل']as$v=>$l):?><option value="<?=$v?>"<?=($settings['otp_send_mode']??'default_text')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label>
          <label>Pattern/Template ID<input name="otp_pattern_id" dir="ltr" value="<?=e($settings['otp_pattern_id']??'')?>"></label>
          <label class="full">متغیرها<input name="otp_variables" dir="ltr" value="<?=e($settings['otp_variables']??'otp,expiry_minutes')?>"></label>
          <label class="full">متن پیام<textarea name="otp_default_text" rows="6"><?=e($settings['otp_default_text'])?></textarea><small>نمونه امن: کد ورود ******، اعتبار ۳ دقیقه</small></label>
        </div><div class="actions"><button class="btn" type="submit">ذخیره تنظیمات OTP</button></div></form>

      <?php elseif($section==='events'):?>
        <?php $sensFa=['service'=>'خدماتی','financial'=>'مالی','confidential'=>'محرمانه','security'=>'امنیتی','legal'=>'حقوقی','public'=>'عمومی','critical'=>'حیاتی','promotional'=>'تبلیغاتی'];$eventTotal=count($events);$eventActive=count(array_filter($events,fn($x)=>!empty($x['default_enabled'])));$securityCount=count(array_filter($events,fn($x)=>($x['sensitivity']??'')==='security'));?>
        <div class="psc-event-summary"><article><strong><?=e($eventTotal)?></strong><span>کل رویدادها</span></article><article><strong><?=e($eventActive)?></strong><span>فعال پیش‌فرض</span></article><article><strong><?=e($eventTotal-$eventActive)?></strong><span>غیرفعال</span></article><article><strong><?=e($securityCount)?></strong><span>رویداد امنیتی</span></article></div>
        <form method="get" action="<?=e(url('plugin/sign-connect/settings/events'))?>" class="psc-event-toolbar"><input name="q" value="<?=e($_GET['q']??'')?>" placeholder="جستجو با عنوان فارسی، کلید فنی یا توضیح"><button class="btn secondary">جستجو</button><a class="btn secondary" href="<?=e(url('plugin/sign-connect/settings/events'))?>">پاک‌کردن فیلتر</a></form>
        <div class="psc-event-catalog"><?php foreach($eventGroups as$category=>$rows):?><details class="psc-event-group" open><summary><span><strong><?=e(\Proma\Plugins\SignConnect\Services\NotificationEventCatalog::CATEGORIES[$category]??$category)?></strong><small><?=e(count($rows))?> رویداد</small></span><span class="badge"><?=e(count(array_filter($rows,fn($x)=>!empty($x['default_enabled']))))?> فعال</span></summary><div class="psc-event-list"><?php foreach($rows as$ev):?><article class="psc-event-row"><div class="psc-event-copy"><strong><?=e($ev['title_fa'])?></strong><p><?=e($ev['description_fa'])?></p><code dir="ltr"><?=e($ev['event_key'])?></code></div><div class="psc-event-meta"><span class="badge" title="سطح حساسیت پیام"><?=e($sensFa[$ev['sensitivity']]??$ev['sensitivity'])?></span><span class="badge <?=$ev['default_enabled']?'badge-light-success':'badge-light-secondary'?>"><?=$ev['default_enabled']?'فعال':'غیرفعال'?></span><small><?=e($ev['source_module'])?></small></div></article><?php endforeach;?></div></details><?php endforeach;?></div>

      <?php elseif($section==='variables'):?>
        <div class="notice info">نام استاندارد داخلی بدون علامت‌های قالب ذخیره می‌شود؛ نمایش هر ارائه‌دهنده از نگاشت مستقل ساخته می‌شود.</div>
        <div class="psc-variable-grid mt-3"><?php foreach($templateVariables as$key=>$definition):?><article><header><div><strong><?=e($definition['title']??$key)?></strong><code dir="ltr"><?=e($key)?></code></div><span class="badge"><?=e($definition['type']??'string')?></span></header><p><?=e($definition['description']??'متغیر استاندارد پیام')?></p><div class="psc-variable-maps"><?php foreach(['ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بله','telegram'=>'تلگرام']as$provider=>$label):?><span><b><?=$label?></b><code dir="ltr"><?=e($variableProviderMappings[$key][$provider]['display']??$key)?></code></span><?php endforeach;?></div></article><?php endforeach;?></div>
        <form class="mt-3" method="post" action="<?=e(url('plugin/sign-connect/variables/save'))?>"><?=csrf_field()?><div class="card-header card-no-border"><h3>افزودن یا ویرایش متغیر</h3></div><div class="form-grid two"><label>نام استاندارد داخلی<input name="variable_key" dir="ltr" pattern="[a-z][a-z0-9_]{2,79}" required placeholder="customer_name"><small>فقط حروف کوچک انگلیسی، عدد و زیرخط؛ بدون #، % یا آکولاد</small></label><label>عنوان فارسی<input name="title_fa" maxlength="190" required></label><label>نوع متغیر<select name="value_type"><option value="string">متن</option><option value="integer">عدد</option><option value="money">مبلغ</option><option value="date">تاریخ</option><option value="url">پیوند</option><option value="otp">کد یکبارمصرف</option></select></label><label>حساسیت<select name="sensitivity"><option value="normal">عادی</option><option value="personal">شخصی</option><option value="financial">مالی</option><option value="secret">محرمانه</option></select></label><label>منبع داده امن<input name="source_resolver" dir="ltr" required placeholder="customer.full_name"></label><label>مقدار نمونه<input name="sample_value" maxlength="500"></label><label class="full">توضیح<textarea name="description_fa" maxlength="500"></textarea></label><fieldset class="full"><legend>نگاشت نام پارامتر ارائه‌دهندگان</legend><div class="form-grid two"><?php foreach(['ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بله','telegram'=>'تلگرام']as$provider=>$label):?><label><?=$label?><input name="mapping[<?=$provider?>]" dir="ltr" placeholder="نام پارامتر بدون delimiter"></label><?php endforeach;?></div></fieldset></div><div class="actions"><button class="btn">ذخیره متغیر و نگاشت‌ها</button></div></form>

      <?php elseif($section==='templates'):?>
        <form method="post" action="<?=e(url('plugin/sign-connect/templates/save'))?>"><?=csrf_field()?><div class="form-grid two">
          <label>رویداد<select name="event_key" required><?php foreach($events as$ev):?><option value="<?=e($ev['event_key'])?>"><?=e($ev['title_fa'])?> — <?=e($ev['event_key'])?></option><?php endforeach;?></select></label>
          <label>کانال<select name="channel"><?php foreach(['in_app'=>'داخل سامانه','ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بله','telegram'=>'تلگرام']as$v=>$l):?><option value="<?=$v?>"><?=$l?></option><?php endforeach;?></select></label>
          <label class="full">متن قالب<textarea name="body" rows="6" required>{customer_name} گرامی، پیام جدیدی در پرما پی دارید.</textarea></label>
          <label>دلیل تغییر<input name="change_reason" maxlength="500"></label>
          <label><input type="checkbox" name="is_active" value="1" checked> قالب فعال باشد</label>
        </div><div class="notice info">متغیرهای مجاز: <span dir="ltr"><?=e(implode(', ',array_keys($templateVariables)))?></span></div><div class="actions"><button class="btn">ذخیره نسخه جدید</button></div></form>
        <div class="table-wrap mt-3"><table><thead><tr><th>کلید قالب</th><th>کانال</th><th>نسخه</th><th>وضعیت</th><th>آخرین تغییر</th></tr></thead><tbody><?php foreach($templates as$t):?><tr><td dir="ltr"><?=e($t['template_key'])?></td><td><?=e($t['channel'])?></td><td><?=e($t['current_version'])?></td><td><?=$t['is_active']?'فعال':'غیرفعال'?></td><td><?=e($t['updated_at'])?></td></tr><?php endforeach;?><?php if(!$templates):?><tr><td colspan="5" class="empty">قالبی ثبت نشده است؛ فرم بالا یک نسخه واقعی ایجاد می‌کند.</td></tr><?php endif;?></tbody></table></div>

      <?php elseif($section==='deliveries'):?>
        <div class="table-wrap"><table><thead><tr><th>شناسه</th><th>ارائه‌دهنده</th><th>مخاطب</th><th>قالب</th><th>وضعیت</th><th>تلاش</th><th>زمان</th></tr></thead><tbody><?php foreach($deliveries as$d):?><tr><td><?=e($d['id'])?></td><td><?=e($d['provider_key'])?></td><td dir="ltr"><?=e(substr($d['recipient_hash'],0,8).'…')?></td><td><?=e($d['template_key']?:'—')?></td><td><span class="badge"><?=e($d['status'])?></span></td><td><?=e($d['attempts'])?></td><td><?=e($d['created_at'])?></td></tr><?php endforeach;?><?php if(!$deliveries):?><tr><td colspan="7" class="empty">رکوردی برای نمایش وجود ندارد.</td></tr><?php endif;?></tbody></table></div><div class="actions mt-3"><a class="btn secondary" href="<?=e(url('plugin/sign-connect/settings/deliveries',['page'=>$deliveryPage+1]))?>">صفحه بعد</a></div>

      <?php elseif($section==='health'):?>
        <div class="table-wrap"><table><thead><tr><th>بررسی</th><th>وضعیت</th><th>شرح</th></tr></thead><tbody><?php foreach($healthRows as$h):?><tr><td dir="ltr"><?=e($h['label'])?></td><td><span class="badge <?=$h['ok']?'badge-light-success':'badge-light-danger'?>"><?=$h['ok']?'سالم':'نیازمند بررسی'?></span></td><td><?=e($h['detail'])?></td></tr><?php endforeach;?></tbody></table></div><div class="notice info mt-3">این صفحه هیچ درخواست خارجی خودکاری ارسال نمی‌کند.</div>

      <?php elseif($section==='retention'):?>
        <div class="notice warning">شواهد، هش‌ها و artifactهای امضای نهایی حذف خودکار ندارند.</div><div class="table-wrap mt-3"><table><thead><tr><th>سیاست</th><th>روز</th><th>حذف مجاز</th></tr></thead><tbody><?php foreach($retentionPolicies as$p):?><tr><td dir="ltr"><?=e($p['policy_key'])?></td><td><?=e($p['retention_days']??'نامحدود')?></td><td><?=$p['can_delete']?'بله':'خیر'?></td></tr><?php endforeach;?></tbody></table></div>

      <?php elseif($section==='audit'):?>
        <div class="table-wrap"><table><thead><tr><th>بخش</th><th>عملیات</th><th>کاربر</th><th>Request ID</th><th>زمان</th></tr></thead><tbody><?php foreach($auditRows as$a):?><tr><td><?=e($a['section_key'])?></td><td><?=e($a['action_key'])?></td><td><?=e($a['actor_id']??'سیستم')?></td><td dir="ltr"><?=e($a['request_id']??'—')?></td><td><?=e($a['created_at'])?></td></tr><?php endforeach;?></tbody></table></div>

      <?php elseif($section==='mfa'): $mp=$modulePolicy['policy'];?>
        <form method="post" action="<?=e(url('plugin/sign-connect/module/mfa/save'))?>"><?=csrf_field()?>
          <div class="notice info">ورود با رمز فعلی حفظ می‌شود. فعال‌سازی سیاست MFA فقط در صورت وجود کانال اصلی معتبر پذیرفته می‌شود.</div>
          <div class="form-grid two mt-3">
            <label>فعال‌سازی سیاست<input type="checkbox" name="enabled" value="1"<?=$modulePolicy['enabled']?' checked':''?>></label>
            <label>حالت MFA<select name="mode"><?php foreach(['disabled'=>'غیرفعال','optional'=>'اختیاری','required_by_role'=>'اجباری براساس نقش','required_for_sensitive_actions'=>'اجباری برای عملیات حساس','required_on_untrusted_device'=>'اجباری برای دستگاه ناشناس','globally_required'=>'اجباری برای همه']as$v=>$l):?><option value="<?=$v?>"<?=($mp['mode']??'disabled')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label>
            <fieldset class="full"><legend>نقش‌های مشمول</legend><div class="switch-options"><?php foreach(['admin'=>'مدیر','operator'=>'اپراتور','lawyer'=>'واحد حقوقی','customer'=>'مشتری']as$v=>$l):?><label><input type="checkbox" name="roles[]" value="<?=$v?>"<?=in_array($v,$mp['roles']??[],true)?' checked':''?>> <?=$l?></label><?php endforeach;?></div></fieldset>
            <label>کانال اصلی<select name="primary_channel"><?php foreach(['smsir'=>'SMS.ir Verify','ippanel'=>'IPPanel OTP','bale'=>'OTP بله','telegram'=>'تلگرام متصل']as$v=>$l):?><option value="<?=$v?>"<?=($mp['primary_channel']??'smsir')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label>
            <label>کانال بازیابی<select name="fallback_channel"><?php foreach(['ippanel'=>'IPPanel','smsir'=>'SMS.ir','bale'=>'بله','telegram'=>'تلگرام','recovery_code'=>'کد بازیابی']as$v=>$l):?><option value="<?=$v?>"<?=($mp['fallback_channel']??'ippanel')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label>
            <label>اعتماد به دستگاه (روز)<input type="number" name="trusted_device_days" min="1" max="90" value="<?=e($mp['trusted_device_days']??30)?>"></label>
            <label>حداکثر دستگاه مورد اعتماد<input type="number" name="max_trusted_devices" min="1" max="20" value="<?=e($mp['max_trusted_devices']??5)?>"></label>
            <label>اعتبار Step-up (دقیقه)<input type="number" name="step_up_minutes" min="2" max="60" value="<?=e($mp['step_up_minutes']??10)?>"></label>
            <label><input type="checkbox" name="sensitive_actions" value="1"<?=!empty($mp['sensitive_actions'])?' checked':''?>> الزام برای عملیات حساس</label>
          </div><div class="actions"><button class="btn">ذخیره سیاست MFA</button><span class="muted">نسخه سیاست: <?=e($modulePolicy['version'])?></span></div>
        </form>

      <?php elseif($section==='otp-security'): $mp=$modulePolicy['policy'];?>
        <form method="post" action="<?=e(url('plugin/sign-connect/module/otp-security/save'))?>"><?=csrf_field()?><input type="hidden" name="enabled" value="1">
          <div class="notice success">این سیاست مستقیماً در ایجاد challengeهای OTP، محدودیت IP/موبایل، cooldown و ابطال challenge قبلی اعمال می‌شود.</div>
          <div class="form-grid three mt-3">
            <?php foreach(['code_length'=>['طول کد',4,8],'ttl_seconds'=>['اعتبار کد (ثانیه)',60,600],'resend_seconds'=>['فاصله ارسال مجدد',30,3600],'max_attempts'=>['حداکثر تلاش',3,10],'hourly_limit'=>['حد ارسال ساعتی',1,30],'daily_limit'=>['حد ارسال روزانه',1,100],'ip_hourly_limit'=>['حد ساعتی هر IP',5,200],'active_challenge_limit'=>['چالش فعال هم‌زمان',1,5],'lock_seconds'=>['مدت مسدودی',60,86400]] as$key=>$meta):?><label><?=e($meta[0])?><input type="number" name="<?=e($key)?>" min="<?=$meta[1]?>" max="<?=$meta[2]?>" value="<?=e($mp[$key]??$meta[1])?>"></label><?php endforeach;?>
            <label><input type="checkbox" name="invalidate_previous" value="1"<?=!empty($mp['invalidate_previous'])?' checked':''?>> ابطال کد قبلی</label>
            <label><input type="checkbox" name="replay_protection" value="1"<?=!empty($mp['replay_protection'])?' checked':''?>> جلوگیری از استفاده مجدد</label>
          </div><div class="actions"><button class="btn">ذخیره سیاست امنیت OTP</button></div>
        </form>

      <?php elseif($section==='signers'):?>
        <div class="table-wrap"><table><thead><tr><th>نوع سند</th><th>نقش</th><th>الزام</th><th>جریان</th><th>ترتیب</th><th>OTP</th><th>انقضا</th></tr></thead><tbody><?php foreach($signerPolicies as$p):?><tr><td dir="ltr"><?=e($p['document_type'])?></td><td dir="ltr"><?=e($p['signer_role'])?></td><td><?=$p['is_required']?'الزامی':'اختیاری'?></td><td><?=$p['workflow']==='sequential'?'ترتیبی':'موازی'?></td><td><?=e($p['sequence_no'])?></td><td><?=$p['otp_required']?'الزامی':'خیر'?></td><td><?=e($p['expires_hours'])?> ساعت</td></tr><?php endforeach;?></tbody></table></div>
        <form class="mt-3" method="post" action="<?=e(url('plugin/sign-connect/module/signers/save'))?>"><?=csrf_field()?><div class="form-grid two">
          <label>نوع سند<select name="document_type"><?php foreach(['contract'=>'قرارداد','amendment'=>'الحاقیه','guarantee'=>'تعهد ضمانت','settlement'=>'اقرار تسویه','legal_notice'=>'اخطار حقوقی','custom'=>'سند سفارشی']as$v=>$l):?><option value="<?=$v?>"><?=$l?></option><?php endforeach;?></select></label>
          <label>نقش امضاکننده<select name="signer_role"><?php foreach(['customer'=>'مشتری','company_representative'=>'نماینده شرکت','guarantor_1'=>'ضامن اول','guarantor_2'=>'ضامن دوم','witness'=>'شاهد','seller'=>'فروشنده','authorized_manager'=>'مدیر مجاز','legal_representative'=>'نماینده حقوقی','custom'=>'سفارشی']as$v=>$l):?><option value="<?=$v?>"><?=$l?></option><?php endforeach;?></select></label>
          <label>جریان امضا<select name="workflow"><option value="sequential">ترتیبی</option><option value="parallel">موازی</option></select></label><label>ترتیب<input type="number" name="sequence_no" min="1" max="20" value="1"></label>
          <label>مهلت امضا (ساعت)<input type="number" name="expires_hours" min="1" max="8760" value="72"></label><label>یادآوری (ساعت)<input type="number" name="reminder_hours" min="1" max="8760" value="24"></label>
          <label><input type="checkbox" name="is_required" value="1" checked> امضاکننده الزامی</label><label><input type="checkbox" name="otp_required" value="1" checked> OTP الزامی</label><label><input type="checkbox" name="typed_name_required" value="1" checked> نام تایپی الزامی</label><label><input type="checkbox" name="drawn_signature_required" value="1"> امضای ترسیمی الزامی</label>
        </div><div class="actions"><button class="btn">ذخیره سیاست امضاکننده</button></div></form>

      <?php elseif($section==='hashes'): $mp=$modulePolicy['policy'];?>
        <form method="post" action="<?=e(url('plugin/sign-connect/module/hashes/save'))?>"><?=csrf_field()?><input type="hidden" name="enabled" value="1"><div class="notice info">مواد کلید نمایش داده نمی‌شوند؛ رکوردهای جدید شماره نسخه کلید را در metadata ثبت می‌کنند و verification تاریخی از کلید محیطی همان نسخه استفاده می‌کند.</div><div class="form-grid two mt-3">
          <label>هش محتوا<select name="algorithm"><option value="sha256">SHA-256</option></select></label><label>HMAC شواهد<select name="hmac_algorithm"><option value="sha256">HMAC-SHA-256</option></select></label>
          <label>Canonicalization<select name="canonicalization"><option value="json-c14n-v1">JSON C14N v1</option></select></label><label>نسخه schema شواهد<select name="evidence_schema"><option value="1">نسخه ۱</option></select></label>
          <label>نسخه فعال کلید<input type="number" name="active_key_version" min="1" max="999" value="<?=e($mp['active_key_version']??1)?>"></label><label>طول اثرانگشت عمومی<input type="number" name="fingerprint_length" min="12" max="32" value="<?=e($mp['fingerprint_length']??16)?>"></label>
          <label><input type="checkbox" name="scheduled_audit" value="1"<?=!empty($mp['scheduled_audit'])?' checked':''?>> پایش زمان‌بندی‌شده یکپارچگی</label>
        </div><div class="actions"><button class="btn">ذخیره سیاست هش</button></div></form>

      <?php elseif($section==='document-versions'): $mp=$modulePolicy['policy'];?>
        <form method="post" action="<?=e(url('plugin/sign-connect/module/document-versions/save'))?>"><?=csrf_field()?><input type="hidden" name="enabled" value="1"><div class="notice success">هسته Proma Pay نسخه‌های قرارداد را در `contract_document_versions` نگهداری می‌کند؛ این سیاست رفتار publication، stale detection و حفاظت نسخه نهایی را محدود می‌کند.</div><div class="form-grid two mt-3">
          <?php foreach(['auto_first_version'=>'ساخت خودکار نسخه اول','new_on_relevant_change'=>'نسخه جدید پس از تغییر مرتبط','stale_detection'=>'تشخیص سند قدیمی','duplicate_prevention'=>'جلوگیری از نسخه تکراری','protect_finalized'=>'حفاظت نسخه نهایی']as$key=>$label):?><label><input type="checkbox" name="<?=$key?>" value="1"<?=!empty($mp[$key])?' checked':''?>> <?=$label?></label><?php endforeach;?>
          <label>نسخه قابل مشاهده مشتری<select name="customer_visible"><?php foreach(['published'=>'منتشرشده','finalized'=>'فقط نهایی','none'=>'عدم نمایش']as$v=>$l):?><option value="<?=$v?>"<?=($mp['customer_visible']??'published')===$v?' selected':''?>><?=$l?></option><?php endforeach;?></select></label>
          <label>آرشیو پیش‌نویس‌ها پس از روز<input type="number" name="archive_drafts_days" min="30" max="3650" value="<?=e($mp['archive_drafts_days']??90)?>"></label>
        </div><div class="actions"><button class="btn">ذخیره سیاست نسخه اسناد</button></div></form>

      <?php elseif($section==='evidence-retention'): $mp=$modulePolicy['policy'];?>
        <form method="post" action="<?=e(url('plugin/sign-connect/module/evidence-retention/save'))?>"><?=csrf_field()?><input type="hidden" name="enabled" value="1"><div class="notice warning">شواهد نهایی، hashها، artifact امضاشده و legal hold از حذف خودکار مستثنا هستند.</div><div class="form-grid three mt-3">
          <?php foreach(['otp_audit_days'=>'Audit کد یکبارمصرف','delivery_success_days'=>'ارسال موفق','delivery_failed_days'=>'ارسال ناموفق','webhook_days'=>'رویداد Webhook','temporary_link_days'=>'لینک موقت','draft_days'=>'پیش‌نویس سند']as$key=>$label):?><label><?=$label?> (روز)<input type="number" name="<?=$key?>" min="<?=$key==='temporary_link_days'?1:7?>" max="3650" value="<?=e($mp[$key]??90)?>"></label><?php endforeach;?>
          <label>اندازه هر batch<input type="number" name="batch_size" min="10" max="500" value="<?=e($mp['batch_size']??100)?>"></label>
          <label><input type="checkbox" name="archive_before_delete" value="1"<?=!empty($mp['archive_before_delete'])?' checked':''?>> آرشیو پیش از پاک‌سازی</label>
          <label><input type="checkbox" name="legal_hold_required" value="1"<?=!empty($mp['legal_hold_required'])?' checked':''?>> بررسی Legal Hold الزامی</label>
        </div><div class="actions"><button class="btn">ذخیره سیاست نگهداری شواهد</button></div></form>

      <?php elseif($section==='signature'):?>
        <form method="post" action="<?=e(url('plugin/sign-connect/settings/save'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="signature"><div class="form-grid two"><label>الگوریتم هش<select name="signature_hash_algorithm"><option value="sha256" selected>SHA-256</option></select></label><label>Canonicalization<input name="signature_canonicalization" readonly value="<?=e($settings['signature_canonicalization'])?>"></label><label>پایش یکپارچگی<select name="integrity_scan_enabled"><option value="1"<?=($settings['integrity_scan_enabled']??'1')==='1'?' selected':''?>>فعال</option><option value="0"<?=($settings['integrity_scan_enabled']??'1')==='0'?' selected':''?>>غیرفعال</option></select></label></div><div class="actions"><button class="btn">ذخیره تنظیمات امضا</button></div></form>

      <?php else:?>
        <div class="empty"><strong>این بخش در منوی تولیدی ارائه نمی‌شود.</strong></div>
      <?php endif;?>
    </div>
  </section>
</div>
<script>
(function(){
  var form=document.querySelector('[data-rules-form]');
  if(!form||form.dataset.ready==='1')return;
  form.dataset.ready='1';
  var dirty=new Set(),label=form.querySelector('[data-dirty-count]');
  form.addEventListener('change',function(event){
    var row=event.target.closest('tr');
    if(row)dirty.add(row);
    if(label)label.textContent=dirty.size?toPersian(dirty.size)+' قانون تغییر کرده و هنوز ذخیره نشده است.':'تغییری ذخیره‌نشده است.';
  });
  form.addEventListener('submit',function(){form.querySelectorAll('button[type="submit"]').forEach(function(button){button.disabled=true;button.textContent='در حال ذخیره…';});});
  function toPersian(value){return String(value).replace(/\d/g,function(d){return'۰۱۲۳۴۵۶۷۸۹'[d];});}
})();
</script>


