from abc import ABC,abstractmethod
class SigningKeyProvider(ABC):
 @abstractmethod
 def key_id(self):...
 @abstractmethod
 def sign(self,payload:bytes)->bytes:...
 @abstractmethod
 def public_key(self)->bytes:...
 @abstractmethod
 def metadata(self)->dict:...
