<?php

return [
    'app_name' => 'پروما',
    'version' => (require __DIR__ . '/version.php')['application'],
    'asset_version' => '1.4.2-rc.1',
    'timezone' => 'Asia/Tehran',
    'base_url' => '',
    'session_name' => 'proma_pay_session',
    'roles' => [
        'admin' => 'مدیر',
        'operator' => 'اپراتور',
        'lawyer' => 'واحد حقوقی',
        'customer' => 'مشتری',
    ],
    'departments' => [
        '' => 'بدون واحد',
        'management' => 'مدیریت',
        'support' => 'پشتیبانی',
        'installments' => 'واحد اقساط',
        'legal' => 'واحد حقوقی',
        'operations' => 'عملیات',
    ],
    'statuses' => [
        'active' => 'فعال',
        'inactive' => 'غیرفعال',
        'pending' => 'در انتظار پرداخت',
        'new' => 'جدید',
        'draft' => 'پیش‌نویس',
        'processing' => 'در حال پردازش',
        'completed' => 'تسویه‌شده',
        'cancelled' => 'لغو شده',
        'reviewing' => 'در حال بررسی',
        'partial' => 'پرداخت جزئی',
        'paid' => 'پرداخت شده',
        'corrected' => 'اصلاح‌شده',
        'overdue' => 'سررسید گذشته',
        'failed' => 'ناموفق',
        'confirmed' => 'تأیید شده',
        'approved' => 'تأیید شده',
        'rejected' => 'رد شده',
        'uploaded' => 'بارگذاری شده',
        'previewed' => 'آماده تأیید',
        'applied' => 'اعمال شده',
        'raw' => 'خام',
        'open' => 'باز',
        'closed' => 'بسته',
        'referred' => 'ارجاع شده',
        'discovered' => 'شناسایی‌شده',
        'update_available' => 'بروزرسانی موجود',
        'removed' => 'حذف‌شده',
        'installed' => 'نصب‌شده',
        'uninstalled' => 'حذف‌شده',
    ],
    'payment_methods' => [
        'manual' => 'پرداخت دستی',
        'zibal' => 'درگاه زیبال',
        'zarinpal' => 'درگاه زرین‌پال',
        'card_transfer' => 'کارت به کارت',
    ],
    'payment_types' => [
        'installment' => 'پرداخت قسط',
        'down_payment' => 'پیش‌پرداخت قرارداد',
    ],
    'legal_stages' => [
        'ابلاغ شده',
        'ثبت دادخواست شکایت',
        'رسیدگی جلسه دادگاه',
        'صدور رای',
        'درخواست اجراییه',
        'ثبت اجراییه',
        'وصول پول',
        'مختومه',
        'رضایت',
    ],
];
