CREATE TABLE IF NOT EXISTS proma_connect_provider_configs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL,
  provider_key VARCHAR(40) NOT NULL,
  title VARCHAR(120) NOT NULL,
  environment VARCHAR(20) NOT NULL DEFAULT 'production',
  external_bot_id VARCHAR(80) NULL,
  external_username VARCHAR(120) NULL,
  encrypted_secret LONGTEXT NULL,
  api_base_url VARCHAR(255) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  capabilities_json LONGTEXT NOT NULL,
  retry_policy_json LONGTEXT NULL,
  health_json LONGTEXT NULL,
  last_tested_at DATETIME NULL,
  last_success_at DATETIME NULL,
  last_failure_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  updated_by BIGINT UNSIGNED NULL,
  updated_at DATETIME NULL,
  archived_at DATETIME NULL,
  UNIQUE KEY uq_provider_uuid (uuid),
  UNIQUE KEY uq_provider_title (provider_key,title,environment),
  KEY idx_provider_state (provider_key,is_active,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS proma_connect_bale_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  delivery_id BIGINT UNSIGNED NULL,
  bale_account_id BIGINT UNSIGNED NOT NULL,
  attempt_uuid CHAR(36) NOT NULL,
  request_id CHAR(36) NOT NULL,
  bot_id VARCHAR(30) NOT NULL,
  masked_recipient VARCHAR(30) NOT NULL,
  message_type VARCHAR(40) NOT NULL,
  message_id VARCHAR(150) NULL,
  status VARCHAR(30) NOT NULL,
  provider_error_code VARCHAR(80) NULL,
  provider_error_name VARCHAR(100) NULL,
  provider_error_description_safe VARCHAR(500) NULL,
  is_retryable TINYINT(1) NOT NULL DEFAULT 0,
  duration_ms INT UNSIGNED NULL,
  attempted_at DATETIME NOT NULL,
  completed_at DATETIME NULL,
  response_snapshot_redacted LONGTEXT NULL,
  UNIQUE KEY uq_bale_request (request_id),
  UNIQUE KEY uq_bale_attempt (attempt_uuid),
  KEY idx_bale_account_status (bale_account_id,status,attempted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS proma_connect_recipient_channel_states (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  recipient_type VARCHAR(30) NOT NULL,
  recipient_id BIGINT UNSIGNED NOT NULL,
  channel VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'unknown',
  last_success_at DATETIME NULL,
  last_unavailable_at DATETIME NULL,
  last_failure_at DATETIME NULL,
  failure_count INT UNSIGNED NOT NULL DEFAULT 0,
  disabled_until DATETIME NULL,
  opted_out_at DATETIME NULL,
  preferences_json LONGTEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uq_recipient_channel (recipient_type,recipient_id,channel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS proma_connect_notification_rules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  event_key VARCHAR(100) NOT NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 0,
  sensitivity VARCHAR(20) NOT NULL DEFAULT 'service',
  recipients_json LONGTEXT NOT NULL,
  channels_json LONGTEXT NOT NULL,
  provider_priority_json LONGTEXT NULL,
  template_key VARCHAR(120) NULL,
  delay_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  quiet_hours_json LONGTEXT NULL,
  max_sends SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  dedupe_seconds INT UNSIGNED NOT NULL DEFAULT 300,
  policy_json LONGTEXT NULL,
  updated_by BIGINT UNSIGNED NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uq_notification_event (event_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS proma_connect_telegram_link_tokens (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  token_hash CHAR(64) NOT NULL,
  token_prefix VARCHAR(12) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  user_type VARCHAR(30) NOT NULL,
  intended_bot_id VARCHAR(80) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  request_id CHAR(36) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  revoked_at DATETIME NULL,
  UNIQUE KEY uq_telegram_token (token_hash),
  UNIQUE KEY uq_telegram_token_request (request_id),
  KEY idx_telegram_token_user (user_id,status,expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS proma_connect_telegram_links (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  user_type VARCHAR(30) NOT NULL,
  bot_id VARCHAR(80) NOT NULL,
  telegram_user_id VARCHAR(80) NOT NULL,
  chat_id VARCHAR(80) NOT NULL,
  username VARCHAR(120) NULL,
  display_name VARCHAR(190) NULL,
  language_code VARCHAR(12) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  linked_at DATETIME NOT NULL,
  verified_at DATETIME NOT NULL,
  last_interaction_at DATETIME NULL,
  last_successful_delivery_at DATETIME NULL,
  last_failed_delivery_at DATETIME NULL,
  failure_count INT UNSIGNED NOT NULL DEFAULT 0,
  notifications_enabled TINYINT(1) NOT NULL DEFAULT 1,
  disconnected_at DATETIME NULL,
  disconnected_by BIGINT UNSIGNED NULL,
  disconnect_reason VARCHAR(500) NULL,
  metadata_json LONGTEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uq_telegram_identity (bot_id,telegram_user_id),
  UNIQUE KEY uq_telegram_chat (bot_id,chat_id),
  KEY idx_telegram_user_state (user_id,user_type,bot_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS proma_sign_hash_registry (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  public_id CHAR(36) NOT NULL,
  request_id BIGINT UNSIGNED NOT NULL,
  signer_id BIGINT UNSIGNED NULL,
  hash_type VARCHAR(40) NOT NULL,
  algorithm VARCHAR(30) NOT NULL DEFAULT 'sha256',
  algorithm_version VARCHAR(20) NOT NULL DEFAULT '1',
  canonicalization_version VARCHAR(30) NOT NULL DEFAULT 'json-c14n-v1',
  digest CHAR(64) NOT NULL,
  authenticity_hmac CHAR(64) NOT NULL,
  previous_event_hash CHAR(64) NULL,
  metadata_json LONGTEXT NULL,
  created_at DATETIME NOT NULL,
  UNIQUE KEY uq_hash_public (public_id),
  UNIQUE KEY uq_hash_type (request_id,signer_id,hash_type),
  KEY idx_hash_chain (request_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS proma_connect_settings_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  section_key VARCHAR(80) NOT NULL,
  action_key VARCHAR(100) NOT NULL,
  actor_id BIGINT UNSIGNED NULL,
  before_json LONGTEXT NULL,
  after_json LONGTEXT NULL,
  request_id VARCHAR(64) NULL,
  created_at DATETIME NOT NULL,
  KEY idx_settings_audit (section_key,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
