from abc import ABC,abstractmethod
class RuntimeStore(ABC):
 @abstractmethod
 def create_session(self,data):...
 @abstractmethod
 def get_session(self,sid):...
class EventStore(ABC):
 @abstractmethod
 def append_event(self,sid,event):...
class CheckpointStore(ABC):
 @abstractmethod
 def latest_checkpoint(self,sid):...
